### ISSUE TITLE
The game cannot be launched without internet connection

### ISSUE THREAD

**Issue by atesin** [skmedix/SKlauncher#109]
**Describe the bug**
the bug described in issue #45 is not really solved, i have no internet and i am affected ..  i haven't found any way to reopen it so i created this one just for get your attention...  please read the last comment from issue #45 , reopen it and discard this

**Comment by thegreatestminer** [comment]
Reading your last comment from that closed issue, you could create a simple script to automatically reset the date modified time for that file before launching it. An example (Windows):

```batch
@echo off
set orig=%cd%
cd %APPDATA%/.minecraft/sklauncher
copy /b sklauncher.data +,,
cd %orig%
java -jar SKLauncher.jar
```

I don't have a computer that has access to Java at the moment, so this may or may not work.

**Comment by Indexerrowaty** [comment]
It's because you don't have Minecraft files for the version you want to open.
