### ISSUE TITLE
Windows showing out of the screen

### ISSUE THREAD

**Issue by TheBigerGamer** [skmedix/SKlauncher#110]
**Describe the bug**
I launched the launcher and it seems normal, but in other windows, it shows out of the screen.

**To Reproduce**
1. Open the launcher
2. Click on 'Edit Profile'
3. See error

**Expected behavior**
The window should appears at the middle of the screen. But it appears out of the screen.

**Screenshots**
![error5](https://user-images.githubusercontent.com/39341546/54077795-7de23000-42b5-11e9-8859-b41df882c05f.PNG)

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 1.8.0_201-b09
 - Launcher Version: 3.0 beta 6

**Comment by skmedix** [comment]
I can't reproduce that, do you have 2 monitors?
