### ISSUE TITLE
SKlauncher wants update every launch

### ISSUE THREAD

**Issue by PetrusTryb** [skmedix/SKlauncher#121]
Every time, when I launch SKlauncher, I see this:
![Zrzut ekranu (158)](https://user-images.githubusercontent.com/8248412/56460602-682c5400-63a5-11e9-915b-5fd5e418fcaa.png)

**Comment by skmedix** [comment]
Update your launcher to **3.0-beta.7**

**Comment by PetrusTryb** [comment]
I already have updated it!

**Comment by skmedix** [comment]
Run launcher with `-console` argument, and post log here

**Comment by PetrusTryb** [comment]
Uh, ok I didn't had known that the file I am downloading from website DOES NOT REPLACE (UPDATE) EXISTING SKlauncher, sorry.
