### ISSUE TITLE
[Game itself] I can't control camera

### ISSUE THREAD

**Issue by NewEarthDeveloper** [skmedix/SKlauncher#122]
The bug is in game. If I should report it somewhere else, please tell me where.

**Describe the bug**
I can't control camera using mouse. I tried to change settings - doesn't work. I can, however, destroy/place blocks or use settings, pause screen buttons etc. normally.

**To Reproduce**
Sadly, I don't know how or why it happens.

**Screenshots**
They won't help.

**Environment:**
 - OS: Windows 10
 - Java Version: 8 update 161
 - Launcher Version: 3.0 beta 7

**Comment by Waterrail** [comment]
If it's an in-game bug, please report it in [Mojang's bug tracker](https://www.google.com/url?sa=t&source=web&rct=j&url=https://bugs.mojang.com/&ved=2ahUKEwix1J3n-fLhAhUulosKHUVlCCYQFjAAegQIBxAD&usg=AOvVaw3zVC5R2c99VNGFtROxJKe-).

**Comment by skmedix** [comment]
It has nothing to do with SKL
