### ISSUE TITLE
Gulliver mod game wont launch

### ISSUE THREAD

**Issue by Thiov** [skmedix/SKlauncher#127]
**Describe the bug**
This problem occurs with forge 1.6.4 and Gulliver mod 1.6.4.
I downloaded the Non-Forge Gulliver mod and selected the correct profile but when I press play it won't launch Minecraft.
The same thing happens with forge 1.6.4.

**To Reproduce**
1. Go to 'https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1282337-mc-forge-1-6-4-gulliver-the-resizing-mod-v0-14-3#download' 
2. Download the Client/Singleplayer (Non-Forge) version and press 'Install client'.
3. Open SKlauncher and select the '1.6.4 Gulliver' profile and press play

**Expected behavior**
I expected it to launch the game

**Screenshots**
Not necessary

**If the bug is launcher related:**
**Environment:**
 - OS: Windows 10
 - Java Version: 8u212
 - Launcher Version: SKlauncher 3-beta.9

**Comment by skmedix** [comment]
Fixed, waiting for confirmation.

**Comment by Thiov** [comment]
It works. Thanks!
