### ISSUE TITLE
Game crash with mods

### ISSUE THREAD

**Issue by Ni3zn4ny1337** [skmedix/SKlauncher#131]
**Describe the bug**
Problem with mods on version 1.12.2. I download forge 1.12.2, optifine 1.12.2, morph mod 1.12.2 and history of technology mod 1.12.2. Select profile is "Forge" but when i click play it won't launch minecraft
**To Reproduce**
1. Go to 'http://www.9minecraft.net/morphing-mod/ http://www.9minecraft.net/history-of-technology-mod/ https://optifine.net/downloads https://files.minecraftforge.net/'
2. Download all and put them into mods (after download forge click on it and press install client)
3. Open Sklauncher select "forge" profile and press play

**Expected behavior**
I expected it to launch the game

**Screenshots**
There are no screenshots
**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: Windows10
 - Java Version: 8
 - Launcher Version: SKlauncher 3-beta.9

**Comment by Kriss7475** [comment]
Please post a crashlog

**Comment by liobarrios** [comment]
no me inicia me pueden ayudar aca dejo mi correo asi me pueden ayudar porfavor lionelbarriospersonal1@gmail.com
You can not help me. I leave my mail so you can help me please.
lionelbarriospersonal1@gmail.com

**Comment by liobarrios** [comment]
Error occurred during initialization of VM
Could not reserve enough space for 1048576KB object heap that's what I get when I play

**Comment by Indexerrowaty** [comment]
Try allocating more RAM. Maybe it will help.

Here's how to do it.
![output-free](https://user-images.githubusercontent.com/39349444/90503865-72ed2980-e150-11ea-8e9f-0231210e6f58.gif)
