### ISSUE TITLE
minecraft 1.14.1 not launching

### ISSUE THREAD

**Issue by heyieiroo** [skmedix/SKlauncher#135]
Error occurred initialization of VM
agent library failed to init: intrument
Error opening zip file or JAR manifest missing : C:\Users\(user name)

**To Reproduce**
after i click play the launcher closes and opens again and then it shows me game output section with the error written above

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50770473/57969178-e49e5c80-797c-11e9-92e0-7a8696892142.png)

[**If](url) the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: windows 7
 - Java Version: 8u211
 - Launcher Version: 3  beta 9

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by heyieiroo** [comment]
i dont know what happened but now it works

**Comment by skmedix** [comment]
Update happened.
