### ISSUE TITLE
Game doesn't start at all

### ISSUE THREAD

**Issue by Selene984** [skmedix/SKlauncher#141]
So I started playing on the SK Launcher 3.0 beta version because apparently 1.13.2 is not compatible with the 2.8.1 version anymore. But the thing is that whenever I click on the start button the launcher shows that it's starting, when, in reality, it does nothing. I'm not able to click on the button again yet the launcher itself doesn't freeze or do anything like it. I'm still able to change the versions despite it saying that the game is launching. Is there a way to fix this or not really?

**Comment by Bleidd64** [comment]
Post the logs please

**Comment by Selene984** [comment]
[16:04:04 INFO]: Launching game
[16:04:04 INFO]: Patching game
[16:04:04 INFO]: Unpacking natives to ///
[16:04:04 INFO]: Launching in ///
[16:04:04 ERROR]: Aborting launch; couldn't create game directory

**Comment by TrueEL** [comment]
Is this your entire log?
If not, post all of it. If yes, then do you have write permission to your game save folder? Or is that a location on a removable disk?
