### ISSUE TITLE
 Skin Help

### ISSUE THREAD

**Issue by RedLizard34** [skmedix/SKlauncher#144]
Hello, I persisted that my skin does not appear on servers and the cover also does not appear. When did you add this feature?
I also have a question: can people who use the launcher see my sklauncher skin?

**Comment by JulieCujoh** [comment]
I changed my skin and I can see my new skin, but the other players can not see my skin they still see that I have the skin steve

**Comment by Indexerrowaty** [comment]
> can people who use the launcher see my sklauncher skin?
Only people who use SKlauncher can see your skin unless using premium account.

**Comment by Indexerrowaty** [comment]
Btw skins should be fixed by now.
