### ISSUE TITLE
Moving the window works only when you drag SKLauncher label on macOS

### ISSUE THREAD

**Issue by Indexerrowaty** [skmedix/SKlauncher#146]
**Describe the bug**
Moving the window does not work when I drag title bar. However when I drag SKlauncher label window does move.

**To Reproduce**
1. Drag window on title bar.

**Expected behavior**
I expected that title bar on drag will make window move.
Only when I drag the window on the SKLauncher label then it works.

**Screenshots**
![SKL bug](https://user-images.githubusercontent.com/39349444/58990721-e07c9680-87e6-11e9-8986-fdb767173013.gif)

**Bug is launcher related:**
**Environment:**
 - OS: MacOS Mojave 10.14.3
 - Java Version: 8u191
 - Launcher Version: 3.0-532d318

**Comment by skmedix** [comment]
Hmm, possibly because logo header uses a different code for moving a window. I'll try to apply the same code to decorator.

**Comment by Indexerrowaty** [comment]
This bug still happens at the latest closed beta (SKL 3.0-0b46bd2)

**Comment by Indexerrowaty** [comment]
Bug fixed!
