### ISSUE TITLE
Elytra has no skin

### ISSUE THREAD

**Issue by Ghastmen** [skmedix/SKlauncher#147]
Uploading a cape don't use the elytra skin its apears as a white box
try to reupload a different cape its not change to the new one 
![2019-06-08_00 06 35](https://user-images.githubusercontent.com/51496504/59136120-fd010600-8981-11e9-9a83-cb439d3b91e3.png)
![2019-06-08_00 06 38](https://user-images.githubusercontent.com/51496504/59136121-fd010600-8981-11e9-91cb-a2be1eae3c95.png)

**Comment by skmedix** [comment]
Post here your cape image

**Comment by Ghastmen** [comment]
its work now and yes i use the old cape that dont have elytra on it but when i try to upload the new one its not change it instantly, but after one or two day its good now 
![2019-06-12_12 10 54](https://user-images.githubusercontent.com/51496504/59343002-2d8eca00-8d0b-11e9-9ec8-19df8db61e4b.png)
