### ISSUE TITLE
My Cape Wont Change

### ISSUE THREAD

**Issue by ThatG4L4XYWolf** [skmedix/SKlauncher#149]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by ThatG4L4XYWolf** [comment]
Sorry im new to GitHub but I cannot change my cape it says it is changed on the website but when I enter launcher on top right it shows steve but in game it shows my skin with my old cape

**Comment by Ghastmen** [comment]
i think i got the same problem but after one or two days its gonna change

**Comment by ThatG4L4XYWolf** [comment]
I fixed it by deleting SKLauncher then deleting my profile changing my Minecraft username (I wanted to change it at one point anyway) then migrating old minecraft premium account to new one reinstalling minecraft running the games once then making a new SKLauncher profile and redownloading SKLauncher and then logging in and it was fixed. (IT WAS A LOT!)
