### ISSUE TITLE
Tłumaczenia w launcherze

### ISSUE THREAD

**Issue by GerbilPL** [skmedix/SKlauncher#151]
Czyżbyś zapomniał ";" na końcu linii? ;)
Coś źle zrobiłeś z tymi string'ami
Tutaj:
![to1](https://user-images.githubusercontent.com/50273945/59301150-3cd13180-8c91-11e9-8ebf-2bfe90ff70e5.png)
i tu:
![to2](https://user-images.githubusercontent.com/50273945/59301166-49558a00-8c91-11e9-959c-c080f98c920d.png)

Co byś zrobił bez bug-trackera, testerów i community...

**Comment by skmedix** [comment]
"Fullscreen" pomimo że ma tłumaczenie, to jest po angielsku ponieważ aktualnie jego szerokość nie jest dostosowywana do długości stringa, a nie chcę widzieć napisu który nie mieści się w oknie.

Natomiast Modal usuwania profili aktualnie nie jest tłumaczony tylko na stabilnej wersji launchera.

---

A tak poza tym, następnym razem zgłaszanie błędu polega **tylko** na zgłoszeniu błędu, więc żarty o średnikach sobie daruj i dostosuj się do szablonu zgłoszenia. ;)
