### ISSUE TITLE
Cannot connect to other player by LAN

### ISSUE THREAD

**Issue by MaciejBaginski** [skmedix/SKlauncher#153]
I can't connect by LAN to another player in network. Our firewalls are turned off and we succesfully can ping each other, but we can't see each other in server list. When trying to connect by "Direct connect" we both get error about Invalid session. 
 - OS: Windows 10
 - Java Version: 1.8.0_191
 - Launcher Version: 3.0-532d318

**Comment by exect3r** [comment]
Check your network adapters. You probably have some virtual ones that the server gets hosted on. Try to disable them and leave only your WiFi / Ethernet adapter on.
