### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by domini8501** [skmedix/SKlauncher#157]
On SK launcher 2.8, you only had to login by writing an username, and that was all. Now, you also have to write an e-mail, and a password. I don't have any e-mails connected to the account that I used before that update. 

Another issue with this new way - when I clicked "log in" to log intro an old account, it got deleted from the list. Please fix this somehow, returning the non - password way (maybe keep the new one, but bring the old method back) as I'm sure that many players are confused on what to do.

**Comment by Fakeowo** [comment]
Domini8501, With e-mail and password, you login to your premium account (i call it as "You bought a copy of Minecraft"). There is an option of playing non-premium aka "cracked minecraft" by marking "Offline" when you try to login. If you don't know how to get there again, head to "Switch User"
I hope I helped you. ^^

Ps.
Head to SKmedix's discord server, you will get there help always.
(Not instant answer, but always in some time ^^)
