### ISSUE TITLE
Maximum RAM Won't Change

### ISSUE THREAD

**Issue by egefff** [skmedix/SKlauncher#161]
I change maximum RAM to 15.5GB from the advanced settings tab. I click save profile and the tab closes. When I re-open the advanced settings tab It goes back to 2GB

I have tried changing to values other than 15.5GB and those didn't also work. 

**To Reproduce**
1. Go to profile settings.
2. Click on Advanced settings.
3. Change max RAM to a value bigger than 2GB.
4. Save profile and close tab.
5. Open Advanced settings again.
6. Max Ram is 2GB.
 
**Environment**
 - OS: Windows 10
 - Java Version:  8u211
 - Launcher Version: Latest version available at this date.

*ALSO*
-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M

are my JVM arguments.

**Comment by skmedix** [comment]
**Confirmed**
Fix inc

**Comment by egefff** [comment]
Whaaa

> **Confirmed**
> Fix inc

If that means fixing: YAY !
If not: What ?

**Comment by skmedix** [comment]
Update with fix is now live

**Comment by egefff** [comment]
> Update with fix is now live

wow how fast. thanks !
