### ISSUE TITLE
Cant start minecraft 

### ISSUE THREAD

**Issue by Wakoer** [skmedix/SKlauncher#162]
**cant start minecraft**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]
![image](https://user-images.githubusercontent.com/52350769/60384404-71a8fb00-9a7d-11e9-8b7f-6f372d558c1c.png)
![Skärmbild (11)](https://user-images.githubusercontent.com/52350769/60384410-8e453300-9a7d-11e9-95fe-c894038dab78.png)
![Skärmbild (11)](https://user-images.githubusercontent.com/52350769/60384413-9309e700-9a7d-11e9-9bf5-36ce180b7875.png)

**Comment by skmedix** [comment]
Not related to launcher.
