### ISSUE TITLE
Automatic Login Feature Without a Token System 

### ISSUE THREAD

**Issue by crispyrussian** [skmedix/SKlauncher#163]
I want a minecraft launcher that is able to run the game and keep the automatic login for both username and password without having a token system. I work in a library that has computers on a program called deep freeze. A program in which reverts the pc aback to an older image i setup for. If i can have automatic login without a token feature that breaks the login in it would be amazing.

**Comment by skmedix** [comment]
Other solution is storing username and password what is VERY insecure. Im not willing to add this.
