### ISSUE TITLE
game crashes instantly, please help

### ISSUE THREAD

**Issue by Baramir10** [skmedix/SKlauncher#171]
as soon as i join a server the game closes and sends me to my desktop, i-m sending the error file

[hs_err_pid7124.log](https://github.com/skmedix/SKlauncher/files/3384661/hs_err_pid7124.log)

**Comment by Baramir10** [comment]
all driver's are up to date btw

**Comment by Ngior** [comment]
crashed all the time, also to me

**Comment by skmedix** [comment]
If updating Intel drivers didn't help, try to increase RAM in your profile, and check Java below 8u60 but not below 8u40
