### ISSUE TITLE
Add a button that disables/enables launcher Auto-Update.

### ISSUE THREAD

**Issue by MGPlayzYT** [skmedix/SKlauncher#172]
This feature is important. This feature should be toggleable.

**Comment by Bleidd64** [comment]
WDYM by auto-update?

**Comment by MGPlayzYT** [comment]
It's this..
Whenever you open the launcher, the first thing you see is "Checking for updates...". That's Auto-Update.

**Comment by skmedix** [comment]
Why you need this
