### ISSUE TITLE
Cant log in 

### ISSUE THREAD

**Issue by Prankster420** [skmedix/SKlauncher#177]
**Describe the bug**
I am triyng to login into Sklauncher 3.0 and it says that my email or my password is wrong but everything is right. I have been trying to change password and reinstalling the launcher but it does not work. I have also made a second account but it does not work either. 

**To Reproduce**
1. Go into Sklauncher 3.0 and login (it says sorry but your username or password is incorrect)

**Expected behavior**
It should just login into the launcher.

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: Java 8 update 191
 - Launcher Version: Sklauncher 3.0-038322c

**Comment by dderpen** [comment]
check offline and write your username

**Comment by Prankster420** [comment]
it works in offline mode. My username is Prankster

**Comment by Indexerrowaty** [comment]
@Prankster420 If your issue was resolved, please close it. Thanks :)
