### ISSUE TITLE
I can't load 1.13 snapshots

### ISSUE THREAD

**Issue by BLCKBRRY** [skmedix/SKlauncher#18]
Hello, i've recently downloaded SKlauncher 2.8.0_37 and i am experiencing an annoying problem when i try to play 1.13 snapshots, right before the game's "Mojang" shows up, the game closes, an error message appears on the laucnher and a crash log (that will be attached) is created. If anyone can help me, i would be  very thankful.
[hs_err_pid3768.log](https://github.com/skmedix/SKlauncher/files/1864884/hs_err_pid3768.log)

**Comment by skmedix** [comment]
Do this error appears in different versions of Minecraft?

**Comment by BLCKBRRY** [comment]
No, just in the 1.13 snapshots

**Comment by skmedix** [comment]
@BLCKBRRY Does the error appears on the 3.0?

**Comment by BLCKBRRY** [comment]
There's a 3.0 version? Where can I download it from?

**Comment by skmedix** [comment]
https://skmedix.pl/sklauncher it's available since yesterday

**Comment by BLCKBRRY** [comment]
Sorry, downloaded it, deleted my previous .minecraft folder and it still doesn't work, am i doing something wrong?

Here's the log:
[hs_err_pid1276.log](https://github.com/skmedix/SKlauncher/files/1876548/hs_err_pid1276.log)

**Comment by skmedix** [comment]
Im not able to reproduce the problem

**Comment by BLCKBRRY** [comment]
That's strange, I'll be attaching a transcript of what appears in the launcher (3.0 beta 4) when i try to load a snapshot (1.13)
[Launcher output.txt](https://github.com/skmedix/SKlauncher/files/1896284/Launcher.output.txt)

**Comment by skmedix** [comment]
Sorry for late reply. Looks like this problem is not launcher related. But I could be wrong

**Comment by BLCKBRRY** [comment]
Oh, is it? if it is, can you tell me what i can do to fix this problem?

**Comment by skmedix** [comment]
```log
# An error report file with more information is saved as:
# C:\Users\Tuco\AppData\Roaming\.minecraft\hs_err_pid5932.log
```

I would like to see this file

**Comment by BLCKBRRY** [comment]
Sure, here it is.
[hs_err_pid5932.log](https://github.com/skmedix/SKlauncher/files/2088264/hs_err_pid5932.log)

**Comment by skmedix** [comment]
Have you tried to update Java & graphics card drivers?
http://support.amd.com/us/gpudownload/Pages/index.aspx
http://support.amd.com/en-us/download/auto-detect-tool
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by BLCKBRRY** [comment]
Thanks man! It worked! Thank you very much!
