### ISSUE TITLE
Crash when spawn in the world

### ISSUE THREAD

**Issue by SlankGolden23** [skmedix/SKlauncher#182]
**Describe the bug**
Crash when spawn in the world

**To Reproduce**
1. Go to the launcher
2. Click on The single player
3. The world is loading 
4. When I spawn in the world the game crash

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Indexerrowaty** [comment]
Add what operating system, launcher version, and Java version you have.

**Comment by Indexerrowaty** [comment]
Closed due to inactivity.
