### ISSUE TITLE
World saves disappear after updating to beta 11

### ISSUE THREAD

**Issue by thepowerfullgalu** [skmedix/SKlauncher#184]
**every world that was on the "saves" folder just disappear if a new profile is loaded**
If a new launcher profile is created using the launcher beta 11, while using this profile any world will not be there to continue, however, using an old profile  all of then appear, even making chages to de old profiles, it still works. this happens because the choosen folder for the game directory is not the ".minecraft" but "C:\Users\arthu\AppData\Roaming\.minecraft\profiles\<profile name>" what makes the launcher recreates the folders that are in the game folder.

Something changed the default configuration folder, after changing it manually didn't happen again Windows 10
Java Version 8u211 64bits
Launcher Version 3.0-038322c

**Comment by Bleidd64** [comment]
That is intended, you can set all profiles to have base game path if you want them to share saves
