### ISSUE TITLE
nie mogę włączyć 

### ISSUE THREAD

**Issue by jarek590** [skmedix/SKlauncher#187]
mam taki problem, że jak chcę włączyć SKluncher to na dole w niebieskim kwadraciku mam ciągle ładowanie i tak cały czas z tego powodu nie mogę włączyć minecrafta 

na zdjęci widać o co mi chodzi.

![to](https://user-images.githubusercontent.com/53969540/62821055-ceb0ca00-bb6e-11e9-922e-159aa65c20ca.png)

**Comment by Indexerrowaty** [comment]
Usuń folder .minecraft i spróbuj ponownie.

**Comment by Indexerrowaty** [comment]
Nie zapomnij zrobić backupu save'ów, shaderów, modów itp.

**Comment by jarek590** [comment]
a co to jest ten backupu save'ów ? i jak to zrobić ?

**Comment by Fakeowo** [comment]
backup save'ów jest to takie coś, że tworzysz kopię folderu i umieszczasz go np. na pulpicie.
save'y, shadery, foldery modów zkopiuj na pulpit i wtedy usuń folder ".minecraft".
Możesz spróbować usunąć pliki z folderu SKLauncher i spróbować go zainstalować ponownie, jak nie zadziała to zrobić jak Indexerrowaty napisał.

Myślę że pomogłem :]
~Fake__

**Comment by Indexerrowaty** [comment]
Zamykam z powodu nieaktywności
