### ISSUE TITLE
my minecraft wont work with optifine.

### ISSUE THREAD

**Issue by reportrakanfurry** [skmedix/SKlauncher#192]
I've download my optifine, and, I've delete forge for this.
My Minecraft can't work with it - because SKLauncher can't find optifine files. I really, really wanna play with shaders (they need optifine) because i'm professional builder. Please help me.

sorry my English isn't the best, because i'm from other country. greetings from Russia!!

**Comment by reportrakanfurry** [comment]
help me!!!

**Comment by Bleidd64** [comment]
install optifine again?

**Comment by reportrakanfurry** [comment]
> install optifine again?

i tried, this can't work...
