### ISSUE TITLE
the launcher close itself while i'm playing

### ISSUE THREAD

**Issue by ghost** [skmedix/SKlauncher#193]
I'm calmly playing and suddenly the launcher close itself and don't save the last information of what I did. It close itself 5 times in a half of an hour and that not allow me to play normally. 

I expect to recieve a solution or what I can do to solve the problem cause is stressful

 - OS:cWindows 10,
 - Java Version: Version 8 upgrade 221 (complilation 1.8.0_221-b11)
 - Launcher Version: 3.0-3abcecd

**Comment by Indexerrowaty** [comment]
This is not a bug.

Click pencil icon.
Click "Game Settings"
Change "Close launcher when game starts" to "Keep the launcher open" or "Hide launcher and re-open when game closes"
Click Save Profile
Done!

**Comment by Indexerrowaty** [comment]
If your problem was resolved close this issue.
