### ISSUE TITLE
My account disappeared and I can only play on DEMO.

### ISSUE THREAD

**Issue by ghost** [skmedix/SKlauncher#194]
At the top left of the launcher home screen (where is the account the person is using) is not with my account. Also, I can only play in Minecraft DEMO and before I could normally.

**Comment by Indexerrowaty** [comment]
This is not a bug. It's because you used original Minecraft Launcher.
Uninstall mojang's launcher. Switch account check offline checkbox and enter your nickname. Then log in. Everything should be now working.

**Comment by KauanRocha** [comment]
Ah ok thanks, in that time you didn't answer my email, I watch a video
and solved my problem.

(if have any word error, considere that i used Google Translate).


Em sex, 30 de ago de 2019 14:33, Dawid <notifications@github.com> escreveu:

**Comment by smalljheremy** [comment]
buenas me puede explicar un poco mejor el problema ya tengo desde hace un mes
