### ISSUE TITLE
Game crashed after connected a server

### ISSUE THREAD

**Issue by Meka4756** [skmedix/SKlauncher#196]
When i try connect "craftrise" server the game crashes or disconnect. But i dont have any problem to connecting other servers.

 Version 1.8.9 (no mod) (offline mode)

[crash-2019-09-04_14.33.09-client.txt](https://github.com/skmedix/SKlauncher/files/3574313/crash-2019-09-04_14.33.09-client.txt)

OS: Windows 7

**Comment by Bleidd64** [comment]
You can try deleting 1.8.9 directory from versions and then it should re-download the version, in case anything is messed up with it. If that doesn't work, please post the server IP and I'll try to recreate the issue

**Comment by Meka4756** [comment]
Thanks . It solved after restarting the game 3 times. It happen sometimes but i think this is not important.

If you want look this server : 

Server ip : play.craftrise.tc
Web site : www.craftrise.tc
