### ISSUE TITLE
error when wanting to start the launcher

### ISSUE THREAD

**Issue by craftraft** [skmedix/SKlauncher#197]
the launcher don't work

**Comment by Bleidd64** [comment]
details?

**Comment by craftraft** [comment]
When the launcher starts don't load minecraft

**Comment by craftraft** [comment]
I cannot configure the settings

**Comment by Bleidd64** [comment]
you press play and then it's stuck on loading or it loads and crashes instantly?

**Comment by Bleidd64** [comment]
you can, right click on profile and press edit profile, there are the settings

**Comment by craftraft** [comment]
I can't pres play because it say loading

**Comment by Bleidd64** [comment]
disconnect from the internet, launch the launcher and when it loads and you can press play i think you can connect again

**Comment by craftraft** [comment]
It works but i can't set options with the launcher

**Comment by Bleidd64** [comment]
don't connect to the internet back then, i think it's possible to set options without connection

**Comment by craftraft** [comment]
It does not let me

**Comment by Bleidd64** [comment]
no idea, i can set optins when i am not connected

**Comment by craftraft** [comment]
I can't set options when i am connected

**Comment by Bleidd64** [comment]
then disconnect, launch launcher and set options, connect and launch game

**Comment by craftraft** [comment]
I won't be taking my computer from the wall every time i want to start the launcher, change the settings or create a new account

**Comment by Sentineell** [comment]
Hi, craftraft, when u click PLAY and during prepraing to start, click Launcher Log, what is your last line in progress?

**Comment by hachimenroppi** [comment]
yup same with me, it says loading and i cant do anything basically, the settings wont even open, as it immediately closes the window itself

**Comment by craftraft** [comment]
I can't click play

**Comment by craftraft** [comment]
The launcher does not stop loading

**Comment by Bleidd64** [comment]
> 
> 
> I won't be taking my computer from the wall every time i want to start the launcher, change the settings or create a new account

This is a temporary issue that has arised in past 2,5h. We don't know when exactly it's going to be fixed but it will be soon. The current workaround (plug the internet out and later in) stays.

**Comment by Sentineell** [comment]
U know, I have problem something like this 
![problem](https://user-images.githubusercontent.com/54904955/64272667-1e04d300-cf40-11e9-8eb7-1d59b4e134f1.PNG)

**Comment by Sentineell** [comment]
Also, I can click play, but it stuck on this line in logs.
