### ISSUE TITLE
Freeze Game because Yggdrasil

### ISSUE THREAD

**Issue by Crosus97** [skmedix/SKlauncher#201]
**Describe the bug**
when are playing with mods the game freeze some times, in the consola appear this message when the game lag
[21:19:30] [Client thread/INFO] [mojang/YggdrasilMinecraftSessionService]: Account XXXXXXX didn't has a texture property

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: W10
 - Java Version: [e.g. 8u221]
 - Launcher Version: 3.0-6ea10ed

**Comment by dderpen** [comment]
that seems like more of a mod issue rather than a launcher issue

**Comment by Indexerrowaty** [comment]
Inactive
