### ISSUE TITLE
The skin doesn't seem to Work (online or offline)

### ISSUE THREAD

**Issue by Enawy** [skmedix/SKlauncher#204]
**Describe the bug**
I downloaded rattman's skin from a site the launcher recognize it and show me the skins Head when i play it then on the latest version of the game nothing appears...I tried multiple skin but none worked...are you sure you added skins to really work

**Comment by Enawy** [comment]
I want to add that my profile is offline

**Comment by D34D-514R** [comment]
Make sure that Compatibility Mode is turned off.

![skinsnotworking](https://user-images.githubusercontent.com/39349444/68493947-c2133f00-024d-11ea-9477-be1e01194ac7.gif)

**Comment by nataria** [comment]
it still isn't working :/

**Comment by Indexerrowaty** [comment]
We experience DDoS attacks so today skins may not work. Try again after some time.

**Comment by nataria** [comment]
thank you ^o^

wt., 17 mar 2020 o 00:26 Dawid <notifications@github.com> napisał(a):

**Comment by Indexerrowaty** [comment]
Skins should be working now.

**Comment by HOMEofCRAFT** [comment]
my skin wont displayed when im offline help me fix this please

**Comment by HOMEofCRAFT** [comment]
> Skins should be working now.

CAn i use my skin in offline mode?
