### ISSUE TITLE
Auto update = Auto delete

### ISSUE THREAD

**Issue by Worsebr** [skmedix/SKlauncher#205]
**Describe the bug**
After auto update all my profiles gone.
**To Reproduce**

**Expected behavior**
Expect keep all my profiles after update, SK delete all even in Shiginima they lost after sk update.

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
Linux Lite (Ubuntu)
 - Java Version: [e.g. 8u181]
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)

 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by D34D-514R** [comment]
Sorry, but I cannot understand you.
Please give more information about the bug.

**Comment by Worsebr** [comment]
The problem seens to be solved already, on new version no more profile loss.
Many updates after this.
