### ISSUE TITLE
game crashes when opening a world

### ISSUE THREAD

**Issue by malakingbayot** [skmedix/SKlauncher#207]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]
![image](https://user-images.githubusercontent.com/55498280/65156406-a36ca500-da61-11e9-91b5-ee11286bad2b.png)

**Comment by Indexerrowaty** [comment]
Allocate more RAM.<hr>Here's how to do it:
![output-free](https://user-images.githubusercontent.com/39349444/90347215-1e05c200-e02f-11ea-948b-cf817d99d5cd.gif)
