### ISSUE TITLE
Capes not working

### ISSUE THREAD

**Issue by KitsuneZenko** [skmedix/SKlauncher#21]
Why does the Cape Or the "Choose Cape" does not work for me when i change the file

**Comment by skmedix** [comment]
It this a problem with the launcher or the website?

**Comment by KitsuneZenko** [comment]
Maybe.. when i choose the skin or cape and login to my account "jcandresUZI124" and i play on a world its just a steve skin with a random cape. I have a 3.0 beta launcher

**Comment by Gbr22** [comment]
My cape only works in singleplayer, and my skin doesn't work in singleplayer (I have premium minecraft, my skin is uploaded there), my skin works in multiplayer, but my cape doesn't. (I have SKL 3)

**Comment by MCnoobix3** [comment]
Use the 2.8 version

l

**Comment by skmedix** [comment]
Capes are supported since 3.0

**Comment by KMGames** [comment]
same problem
