### ISSUE TITLE
hi i was about to change my skin/cape but the website (google crome in windows 10)it did not let me in and there was a warning text saying attention account ban by server admin and y tried oter ways to enter the website but it did not let me in,  please tell me what to do in order to get back in true stament LegoChanel456_YT

### ISSUE THREAD

**Issue by LegoChanel456** [skmedix/SKlauncher#218]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Indexerrowaty** [comment]
Looks like you got banned on SKLauncher website for some reason.

@skmedix

**Comment by skmedix** [comment]
Duplicate https://github.com/skmedix/SKlauncher/issues/217

@D34D-514R Also not true, you cant be banned at SKL
