### ISSUE TITLE
profiles not working

### ISSUE THREAD

**Issue by Ysn-S** [skmedix/SKlauncher#222]
when i try to make a profile it doesnt make a profile folder or anything

1. Go to the plus where you make profiles
2. Create a new profile
3. Check the minecraft folder

it's meant to make a seperate folder for mods, texture packs etc

this bug is launcher-related

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 1.8.0_171-b11
 - Launcher Version: 3.0-9dadd19

not website related

**Comment by Bleidd64** [comment]
You need to launch the game, it will make the folder then
