### ISSUE TITLE
error message when i start the game

### ISSUE THREAD

**Issue by agusthye** [skmedix/SKlauncher#227]
everytime i press "play" this message below appears, please help me!

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 28/11/19 16:43
Description: Initializing game

java.lang.IllegalStateException: The driver does not appear to support framebuffer objects
	at com.mojang.blaze3d.platform.GLX.init(SourceFile:438)
	at cyc.au(SourceFile:482)
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX.init(SourceFile:438)
	at cyc.au(SourceFile:482)

-- Initialization --
Details:
Stacktrace:
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 402055328 bytes (383 MB) / 587202560 bytes (560 MB) up to 1073741824 bytes (1024 MB)
	CPUs: 2
	JVM Flags: 10 total; -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx1024m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Launched Version: 1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: Intel Bear Lake B GL version 1.4.0 - Build 8.14.10.1930, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by D34D-514R** [comment]
Update your drivers.
If this doesn't help or you have already drivers up to date then it means you need to upgrade your PC ¯\_(ツ)_/¯.
