### ISSUE TITLE
Skin function doesn't really work

### ISSUE THREAD

**Issue by Mell-PL** [skmedix/SKlauncher#233]
I don't have any mods, also the compatibility mode is off, i don't know what could cause this bug, so probably it's launcher fault. I hope you'll fix it soon! also, i'm playing offline!

**Comment by NightFurySL2001** [comment]
Skin function may require internet connection to load your skin from SKMedix server. Please check if your computer is connected to internet before starting Minecraft.

**Comment by Mell-PL** [comment]
> Skin function may require internet connection to load your skin from SKMedix server. Please check if your computer is connected to internet before starting Minecraft.
I always have my computer connected to the internet, I tried today and it still didn't worked.

**Comment by Indexerrowaty** [comment]
Our servers are overloaded due to recent events.

**Comment by Indexerrowaty** [comment]
Fixed
