### ISSUE TITLE
I can't choose a mc version

### ISSUE THREAD

**Issue by Kacperzglaszaproblemgry** [skmedix/SKlauncher#240]
New launcher version
Mac OS

I can't choose a mc version
no one is on the list

**Comment by skmedix** [comment]
Post `.minecraft/sklauncher/sklauncher.log`

**Comment by D34D-514R** [comment]
Jaką masz wersję macOS'a?
I wyślij tutaj logi z SKlaunchera które znajdziesz tu:
`~/Library/Application Support/minecraft/sklauncher/sklauncher.log`
