### ISSUE TITLE
I do not know why I was banned. I just created my account last 2 days and The server said my account was banned. My name is Vincere

### ISSUE THREAD

**Issue by vincere123** [skmedix/SKlauncher#242]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Bleidd64** [comment]
The whole site is down, not your account. Please join our Discord to stay updated: https://discord.gg/fXB22jm
medix is offline atm, only he can resolve the issues

**Comment by Bleidd64** [comment]
The site is now back up
