### ISSUE TITLE
bug na tentativa de mudar a skin no sklauncher

### ISSUE THREAD

**Issue by felipe9346** [skmedix/SKlauncher#248]
*how is bug*
ele aparece que mudou no site mas quando entro no jogo estou com a skin do steve

1. Go to 'SK launcher'
2. Click on 'play'
3. 'enter a world'
4. See skin error

**Expected behavior**
correct skin

**Comment by Bleidd64** [comment]
Closed as non-English. I will reopen the issue if you give more info, but it needs to be in English
