### ISSUE TITLE
IF I WANT MC LAUNCHER TO HAVE FREE MC THEN WHY LAUNCHER GIVES ME ONLY A DEMO

### ISSUE THREAD

**Issue by ivvanskyy** [skmedix/SKlauncher#250]
![1](https://user-images.githubusercontent.com/61709749/76710435-d4bfe800-6707-11ea-83a9-ff3b2f267759.PNG)
![2](https://user-images.githubusercontent.com/61709749/76710440-db4e5f80-6707-11ea-92f1-923ca803aa89.PNG)
![3](https://user-images.githubusercontent.com/61709749/76710449-e4d7c780-6707-11ea-94c4-79549d622622.PNG)
![4](https://user-images.githubusercontent.com/61709749/76710452-e99c7b80-6707-11ea-989b-93280e121cb3.PNG)
 
WHY I ONLY CAN USE DEMO? WHATS THE POINT OF LAUNCHER IF I CANT PLAY IT FREE

**Comment by Indexerrowaty** [comment]
Check offline checkbox when logging into the launcher
