### ISSUE TITLE
the site does not load the 490 request in excess.

### ISSUE THREAD

**Issue by larson21** [skmedix/SKlauncher#252]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by larson21** [comment]
the site does not load the 490 request in excess.

**Comment by larson21** [comment]
![image](https://user-images.githubusercontent.com/62353401/76995089-1c27bd80-692e-11ea-9eb2-ecf682af1d03.png)

**Comment by larson21** [comment]
the site does not load the 490 request in excess.

**Comment by Indexerrowaty** [comment]
We are experiencing DDoS attacks so that's why it shows 429 error.

**Comment by larson21** [comment]
please help me!

**Comment by larson21** [comment]
> Estamos enfrentando ataques DDoS, é por isso que mostra o erro 429.

Thanks

**Comment by Indexerrowaty** [comment]
No problem :)

**Comment by larson21** [comment]
more when it goes back to normal ??

**Comment by Indexerrowaty** [comment]
I don't know. When the person which is responsible for DDoS attacks will stop.

**Comment by larson21** [comment]
thank you, but do you defend yourself?

**Comment by Indexerrowaty** [comment]
SKmedix is doing his best to stop these attacks to happen.

**Comment by larson21** [comment]
thank you very much helped a lot

**Comment by Indexerrowaty** [comment]
No problem :)

**Comment by larson21** [comment]
hello

**Comment by larson21** [comment]
tthe site is having another attack ???

**Comment by larson21** [comment]
because he was working and then he is no longer

**Comment by larson21** [comment]
was working**

**Comment by larson21** [comment]
working

**Comment by Indexerrowaty** [comment]
It sometimes works sometimes not.

**Comment by larson21** [comment]
![image](https://user-images.githubusercontent.com/62353401/77000322-f4892300-6936-11ea-8a97-f7f0303d958d.png)

**Comment by larson21** [comment]
look

**Comment by larson21** [comment]
he val back to normal ??

**Comment by Indexerrowaty** [comment]
Everything is back to normal
