### ISSUE TITLE
SKlauncher 3 beta 15 opens the news page in web browser infinitely

### ISSUE THREAD

**Issue by UDPSendToFailed** [skmedix/SKlauncher#254]
**Describe the bug**

As the title says. After launching SKlauncher, it starts to open thousands of tabs repeatedly with it's news page in the web browser, making almost impossible to stop it.

**To Reproduce**

Run SKlauncher 3 beta 15

**Expected behavior**

News site displayed inside SKlauncher instead of default browser

**Screenshots**

![kép](https://user-images.githubusercontent.com/16057404/77170947-0ea03e00-6abc-11ea-8b16-6e1e44fca736.png)

**If the bug is launcher related:**
**Environment (please complete the following information):**

 - OS: Windows 10 18363.720
 - Java Version: 8u241 x64
 - Launcher Version: latest, 3 beta 15

**Comment by Bleidd64** [comment]
It's a known bug and we are working on fixing it.
