### ISSUE TITLE
SKLauncher 3-beta 15

### ISSUE THREAD

**Issue by Szarzasty** [skmedix/SKlauncher#255]
Hi. I have downloaded a new launcher and when i want to open him, the google started opening a 10 web for a 1 sec: http://web.skmedix.pl/skl-news/?dark=false
I cant start the game.. what a bug?

**Comment by Bleidd64** [comment]
It's a known bug and we are working on fixing it.
Temporary workaround: Disconnect internet, open SKL, connect internet

**Comment by Szarzasty** [comment]
I thought so to do it .. I hope you will quickly remove the error, because I almost exploded my computer from this number of pages. Regards.
