### ISSUE TITLE
bug site

### ISSUE THREAD

**Issue by larson21** [skmedix/SKlauncher#257]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by larson21** [comment]
![image](https://user-images.githubusercontent.com/62353401/77173789-d3434680-6a9e-11ea-8bcf-a66baf9de9de.png)

**Comment by larson21** [comment]
Unfortunately the bug continues

**Comment by Indexerrowaty** [comment]
It's a known bug.
The fix is coming.
Temporary solution: Disconnect from internet your computer and then run SKL.
