### ISSUE TITLE
Issue with request of home page [SKlauncher 3..0 beta.15]

### ISSUE THREAD

**Issue by WoodenGuy** [skmedix/SKlauncher#258]
**Describe the bug**
Content of news page instead of loading in launcher pop up in web browser and spams it.

**To Reproduce**
Just open a launcher

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [ Windows 10, ]
 - Java Version: [ 8u181]
 - Launcher Version: [ 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser: [ Chrome 68]

**Comment by Bleidd64** [comment]
Known bug, fix incoming
Temporary workaround: Disconnect internet (unplug the cable), open SKL, connect internet
