### ISSUE TITLE
Skin wont load after reinstalling my whole system

### ISSUE THREAD

**Issue by Lucijan2342** [skmedix/SKlauncher#263]
So today i was going to do a fresh new restart to my system and yea then after a while i installed Sklauncher then i went to change my skin so i changed it and i changed my cape i saved the settings then my cape was invisible and my skin how do i fix thisssssssssssss

**Comment by Lucijan2342** [comment]
PLZZZZZZZZZZZZZZZZZ

**Comment by Indexerrowaty** [comment]
Skins were disabled before.
