### ISSUE TITLE
skin bug

### ISSUE THREAD

**Issue by larson21** [skmedix/SKlauncher#267]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Indexerrowaty** [comment]
Q: Website/skins are not working
A: It's because our servers are overloaded due to recent events

**Comment by larson21** [comment]
![image](https://user-images.githubusercontent.com/62353401/77823378-774d7300-70d9-11ea-9372-107abbeeef80.png)

**Comment by larson21** [comment]
I want to know when it goes back because I want to record my videos

**Comment by Indexerrowaty** [comment]
We don't know.
Sorry for inconvenience.

**Comment by larson21** [comment]
but when will it come back?

**Comment by Indexerrowaty** [comment]
> skins are going to be disabled for few hours/days until we find a better solution for super high traffic.
~ SKmedix
