### ISSUE TITLE
The skins feature doesnt work even after the update.

### ISSUE THREAD

**Issue by FacetimeDog** [skmedix/SKlauncher#268]
So in the web page appears my Skin but in the launcher doesnt, in game doesnt work either
yes, im using Internet connection while using the launcher, and i changed the skin before the skins were disabled, i tried logging out and logging in many times didnt work.
Screenshots:

![Screenshot](https://user-images.githubusercontent.com/63069960/78288806-34c7d400-74e7-11ea-8b2f-99506edf3997.png)

![Screenshot1](https://user-images.githubusercontent.com/63069960/78289057-45784a00-74e7-11ea-8806-3b44b94a6afb.png)

 - OS: Windows 10
 - Java Version: 1.8.0_241 (Java 8)
 - Launcher Version:  3.0-1a97ead
 - Browser: Google Chrome

**Comment by Angelo5001** [comment]
me pasa lo mismo, la skin me aparece en la pagina y en el lanzador pero al entrar el juego y abrir un mundo me sale alex o steve pero no me sale mi skin.

**Comment by Bleidd64** [comment]
Skins are disabled

**Comment by Indexerrowaty** [comment]
Soon™ in July everything will work as it should be.

**Comment by Indexerrowaty** [comment]
Fixed
