### ISSUE TITLE
IPv6 not supported

### ISSUE THREAD

**Issue by PetrusTryb** [skmedix/SKlauncher#269]
**Describe the bug**
When I am trying to connect to an IPv6 server, I see "protocol family unavaiable" error.
IPv6 works in original Minecraft Launcher.

**To Reproduce**
1. Open SKlauncher and launch Minecraft
2. Try to connect to any IPv6 server (for example Your local)
3. You will see "protocol family unavaiable error"

**Expected behavior**
I want to be able to connect servers over IPv6.

**Screenshots**
![Zrzut ekranu (148)](https://user-images.githubusercontent.com/8248412/78552847-81bdea00-7808-11ea-93e3-cc71dbad97bb.png)

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 1.8.0_232
 - Launcher Version: 3.0-1a97ead

**Comment by Bleidd64** [comment]
We were able to reproduce the issue and are currently investigating it.

**Comment by skmedix** [comment]
**Fixed**, now you can remove `-Djava.net.preferIPv4Stack=true` from game arguments
![image](https://user-images.githubusercontent.com/3246162/85882379-7c58b600-b7df-11ea-90a1-09923ef50998.png)
