### ISSUE TITLE
Capes and skins not working properly

### ISSUE THREAD

**Issue by Gbr22** [skmedix/SKlauncher#27]
My cape only works in singleplayer, and my skin doesn't work in singleplayer (I have premium minecraft, my skin is uploaded there), my skin works in multiplayer, but my cape doesn't. (I have SKL 3)
Singleplayer: https://i.imgur.com/eILfCHH.png
Multiplayer: https://i.imgur.com/HD1AmDv.png

**Comment by Bleidd64** [comment]
Closed as inactive
