### ISSUE TITLE
ISUE CAN'T LOGIN

### ISSUE THREAD

**Issue by oldziaa4** [skmedix/SKlauncher#270]
4.  registered on the site, now I log in and write that there is a wrong password or email.  I tried offline, I have the latest jave, I uninstalled.  I've been doing it for 2 days and still nothing 
![image](https://user-images.githubusercontent.com/63307472/78693306-5c5dd880-78fb-11ea-8a06-63b122e0d705.png)

**Comment by Bleidd64** [comment]
Check 'Offline' and type in our username instead of email. As you can see, without Offline is login for a Mojang account, not SKL one.
