### ISSUE TITLE
Minecraft is not opening

### ISSUE THREAD

**Issue by zubziauwu** [skmedix/SKlauncher#274]
So basically, I've played mc today and it was totally fine. But when I wanted to play now, minecraft didn't open. Script says: "Gave up trying to download https://libraries.minecraft.net/optifine/OptiFine/1.15.2_HD_U_G1_pre9/OptiFine-1.15.2_HD_U_G1_pre9.jar for job 'Version & Libraries'". I don't really know what to do. 
I work on Windows 10.

**Comment by Indexerrowaty** [comment]
Try reinstalling OptiFine.
