### ISSUE TITLE
Minecraft Lan not working between PCs on the same network

### ISSUE THREAD

**Issue by HiroNoshimuri** [skmedix/SKlauncher#278]
Minecraft Lan not working between PCs on the same network
Error: Failed to log in: Invalid session

1. Open Launcher with the desired profile on two devices
2. Create a world on one device and select the Open to LAN option in the menu
3. Select the Multiplayer play on the other device and write the IP address of the other PC and the designated port
4. Wait to connect until you receive the error

Expected: The other user connects to the LAN server with no difficulty

Bug observed in Minecraft version 1.15.2, SK Launcher version 3.0-1a97ead
Attempted to connect both ways with no success
Issue also observed with external servers

![f30a52249bb8b01b60d6119301996ce6](https://user-images.githubusercontent.com/63591949/79120472-ac291d80-7d9b-11ea-8623-a408a7933f01.png)

**Comment by LONGACAT** [comment]
It means that the server detected that you are not logged in with a Mojang account. External servers that you tried to join also verify the Mojang account.
Try running the host in offline mode (as in unplugging the Pc from the internet temporaily). Or you can host a server using jars provided on the minecraft site and set `online-mode` to `false` in server.properties
