### ISSUE TITLE
Minecraft screenshots dont show up on my computer

### ISSUE THREAD

**Issue by Oratus222** [skmedix/SKlauncher#279]
when i click F2 in minecraft it says that the screenshot is taken but it dont show anywhere on my computer i went to %appdata%/.minecraft/screenshots  and there was no screenshots

**Comment by LONGACAT** [comment]
You might be using a profile with custom game directory. Go into .minecraft/profiles/Name of your profile/screenshots, it should be there.

**Comment by Oratus222** [comment]
ok ill try

**Comment by Oratus222** [comment]
omg thank u very very much 
u solved my problem ily <3
