### ISSUE TITLE
po otworzeniu sk launchera usuwają się światy

### ISSUE THREAD

**Issue by bartkol1** [skmedix/SKlauncher#280]
Po ponownym odpaleniu launchera usuwają się ostatnie profile.
Spodziewałem się, że profile, które stworzyłem zachowają się i nie będą się usuwać.
![Uploading 2020-04-20 (64).png…]()

**Comment by Indexerrowaty** [comment]
Nic nie grzebałeś przy folderze profiles albo sklauncher w .minecraft?
