### ISSUE TITLE
Can't play at Minecraft servers (minecraft 1.15.2

### ISSUE THREAD

**Issue by RawrTV** [skmedix/SKlauncher#282]
The problem is i can't play on minecraft servers .
The error call 

> Failed to log in: Invalid session

**Specification**

> Java (build 1.8.0_251-b08)

> Windows 10  Home x64

> 8 GB RAM

**Comment by LONGACAT** [comment]
You are trying to play on a server which authenticates users on Mojang servers. If you are the admin of that server, set `online-mod` to `false` in `server.properties`.
