### ISSUE TITLE
Nie można grać na serwerach Minecraft (Minecraft 1.15.2

### ISSUE THREAD

**Issue by RawrTV** [skmedix/SKlauncher#283]
Problem polega na tym, że nie mogę grać na serwerach Minecraft.
Wywołanie błędu

> Logowanie nie powiodło się: nieprawidłowa sesja

**Specyfikacja**

> Java (kompilacja 1.8.0_251-b08)

> Windows 10 Home x64

> 8 GB pamięci RAM

**Comment by LONGACAT** [comment]
Próbujesz grać na serwerze, który wymaga zalogowania do konta Mojang. Jeśli jesteś administratorem tego serwera ustaw `online-mode` na `false` w `server.properties`

**Comment by RawrTV** [comment]
thx
