### ISSUE TITLE
Furnace,crafting table guis, and othes things lost texture

### ISSUE THREAD

**Issue by kaikeamv** [skmedix/SKlauncher#284]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Indexerrowaty** [comment]
Turn off custom texture packs. If this will not help/you don't have any texture packs reinstall Minecraft by deleting `.minecraft` and running the game again.
Don't forget to make backup of your saves, shaders, texture packs etc.

If it helped please close this issue.
