### ISSUE TITLE
"Прифили" instead of  "Профили" 

### ISSUE THREAD

**Issue by auto-septik** [skmedix/SKlauncher#286]
**Describe the bug**
Error in russian translation.
"Прифили" instead of  "Профили" 

**To Reproduce**
1. Choose russian translation
2. Reload launcher
3. See the lable at main screen

**Screenshots**
![изображение](https://user-images.githubusercontent.com/34984880/81322267-63177100-909c-11ea-8278-35e8be16d778.png)
![изображение](https://user-images.githubusercontent.com/34984880/81322511-c7d2cb80-909c-11ea-95b7-4c1011fb0c5b.png)

**If the bug is launcher related:**
**Environment**
 - OS: Windows 10
 - Java Version: Don't related
 - Launcher Version: 3.0-1a97ead

**Comment by Indexerrowaty** [comment]
You mean that this `Профили` is correct translation?

**Comment by NiksonBinsk** [comment]
> 
> 
> You mean that this `Профили` is correct translation?

Yup
