### ISSUE TITLE
VRAM Use Minecraft

### ISSUE THREAD

**Issue by Feexi** [skmedix/SKlauncher#289]
Hey! I was using SK-Launcher for a long time, after a format of pc, i've got a huge problem.
I can't give more VRAM For minecraft than 1gb. 
The problem wasn't happening before format, please help!

(I attach a picture of it here!)
![321](https://user-images.githubusercontent.com/62441025/81934299-0ad9f500-95ef-11ea-94f7-3c066040d1a4.png)

**Comment by Indexerrowaty** [comment]
Pobierz I zainstaluj wersję 64-bitową (x64) Javy.

**Comment by Feexi** [comment]
> Pobierz I zainstaluj wersję 64-bitową (x64) Javy.

Nie dziala, nową jave ogarnalem.

**Comment by Feexi** [comment]
Okay, problem is ended. I've found out what was the problem.
Closing this issue!

**Comment by Indexerrowaty** [comment]
K
