### ISSUE TITLE
skin not changing

### ISSUE THREAD

**Issue by CYBERVERST** [skmedix/SKlauncher#292]
**Describe the bug**
i changed my skin on the website and it saved. on the menu of the launcher it had my new skin, but in game i still had my old skin. please fix this.

**Comment by Indexerrowaty** [comment]
> Skins are disabled due to high traffic and will stay disabled until further notice.

**Comment by Linkshu1** [comment]
When you go to the website to change your skin, click remove skin first then save settings, then choose the skin you want to use then save settings. I had the same problem too, hope this helps you!

**Comment by Indexerrowaty** [comment]
> > Skins are disabled due to high traffic and will stay disabled until further notice.

Should be fixed now.
