### ISSUE TITLE
[Suggestion] Add the AppImage download

### ISSUE THREAD

**Issue by ItzLightyHD** [skmedix/SKlauncher#293]
I made an AppImage for SKLauncher with Java included, i hope I can help you with this.
If you download it, just give execute permissions, and you're ready to go.
NOTE: If you want to use the dedicated graphics card, open the terminal and execute "DRI_PRIME=1 ./SKLauncher.AppImage" (without quotes, please)

→ Download here: https://itzlightyhd.cf/dl/SKLauncher.AppImage

**Comment by LONGACAT** [comment]
I can't download the file. After downloading about 80 MB it fails. Can you please re-host it?

**Comment by ItzLightyHD** [comment]
Try this: https://archiviodilighty.imfast.io/SKLauncher.AppImage

**Comment by ItzLightyHD** [comment]
> I can't download the file. After downloading about 80 MB it fails. Can you please re-host it?

Try it again, I fixed it, or just go here: https://archiviodilighty.imfast.io/SKLauncher.AppImage

**Comment by LONGACAT** [comment]
Works quite good from what I've tested. I'll let you know if we add it
