### ISSUE TITLE
Fullscreen bug

### ISSUE THREAD

**Issue by Ksawi999** [skmedix/SKlauncher#296]
My fullscreen fills more than all of the screen. How I can repair that?

**Comment by LONGACAT** [comment]
Below instructions are for Windows 10, as you did not specify operating system.

Check the scale percentage by right-clicking on your desktop and pressing `Display settings`. Under `Scale and layout` there is a drop-down menu. If it's above 100%, you can either set it to 100% or do this:
1. Find your java installation (example - `C:\Program Files\Java\jre8\bin`)
2. Right click on the javaw.exe and press `Properties`
3. On the `Compatibility` tab press `Change High DPI settings`
4. Tick `Override high DPI scaling behavior`, select `Application`
