### ISSUE TITLE
Forge and Optifine always crash

### ISSUE THREAD

**Issue by Linkshu1** [skmedix/SKlauncher#298]
Describe the bug
Every time i try to use forge or Optifine on any version of Minecraft in multiplayer my MInecraft always crashes. Is there a way to fix this?

I am using Windows 7(64-bit)
My launcher version is 3.0-1a97ead (Latest version of the launcher)

**Comment by Indexerrowaty** [comment]
Some multiplayer servers do not allow Forge. Try installing optifine only. Unless that server uses forge mods. Then please attach crash log.

You can also join our Discord server for fast support https://discord.gg/whVhJk6

**Comment by Linkshu1** [comment]
Thank you very much! Optifine has finally worked, although for the newer versions of minecraft like 1.14 and 1.15 it still does not work although this might be because my pc is not meant for gaming.

**Comment by Indexerrowaty** [comment]
No problem ;)

**Comment by Indexerrowaty** [comment]
Please close the issue.
