### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by hayavocado** [skmedix/SKlauncher#299]
hi!
i do not know why, but i have strange problem. when i start loading the game, i always see the moyang's logo and when minecraft has loading, it stops in the half. i dont know what i can do with it and i thought the best way will be write to you. 
have a good day Oliwia.
ps. if i did some language mistakes i'm so sorry, my English is low.

**Comment by Indexerrowaty** [comment]
Gdy startujesz grę to powinnaś mieć w sklauncherze zakładkę "Dziennik gry (nazwa profilu)".
Wejdź w nią i zrób screenshota i wyślij go tu.

When you start the game there should be in sklauncher "Game output (profile name)" tab.
Click on it and take a screenshot then send it there.
