### ISSUE TITLE
cape is showing in the customization ,but not in game,i am in 1.8.9 ,is it becuz the version.

### ISSUE THREAD

**Issue by Dakillermoth** [skmedix/SKlauncher#301]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Dakillermoth** [comment]
the cape is not being displayed in game 
version 1.8.9
widows 10
skl 3
plz help

**Comment by Indexerrowaty** [comment]
Capes are DISABLED due to high traffic

**Comment by Dakillermoth** [comment]
oh ok
