### ISSUE TITLE
Minecraft Nie Chcę mi Odpalić od Dłuszego Czasu help 

### ISSUE THREAD

**Issue by Playerrrrrrrrrr** [skmedix/SKlauncher#302]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Playerrrrrrrrrr** [comment]
Minecraft nie chce mi kurna odpalic help

**Comment by Indexerrowaty** [comment]
Usuń C:\\WINDOWS wtedy na 100% zadziała

**Comment by Playerrrrrrrrrr** [comment]
pierdol się :)

sob., 6 cze 2020 o 16:38 Dawid <notifications@github.com> napisał(a):

**Comment by LONGACAT** [comment]
Proszę o więcej informacji, najlepiej uzyskać pomoc na naszym [Discordzie](https://discord.gg/BdCcpDZ). Nie mamy możliwości pomocy bez jakiegokolwiek opisu poza "nie działa"

**Comment by Playerrrrrrrrrr** [comment]
poprostu nie działa ;-; nie włacza się i tyle co jeszcze chcecie wiedzieć
-_- ?

niedz., 7 cze 2020 o 18:38 LONGACAT <notifications@github.com> napisał(a):

**Comment by dderpen** [comment]
wow NA PEWNO ci pomożemy z taką ilością informacji po prostu idealnie
tak serio to nic z tego nie wynika że powiesz że nie działa bo musimy wiedzieć CZEMU więc wyślij crashlog

**Comment by LONGACAT** [comment]
System operacyjny, wersja javy, sklauncher.log i/lub crash log to takie niezbędne minimum

**Comment by Playerrrrrrrrrr** [comment]
pierdolcie się :)

pon., 8 cze 2020 o 10:17 LONGACAT <notifications@github.com> napisał(a):

**Comment by Playerrrrrrrrrr** [comment]
Pierdolcie się :)

pon., 8 cze 2020 o 10:03 dderpen <notifications@github.com> napisał(a):

**Comment by Playerrrrrrrrrr** [comment]
Wow bo NA PEWNO będę korzystała z waszych usług przez wasze usługi i
odnoszenie się do ludzi :)

pon., 8 cze 2020 o 10:03 dderpen <notifications@github.com> napisał(a):

**Comment by Playerrrrrrrrrr** [comment]
[image: image.png]

Masz i rzyj karakanie

pon., 8 cze 2020 o 10:03 dderpen <notifications@github.com> napisał(a):

**Comment by LONGACAT** [comment]
Ok, nie to nie, radź sobie sam, a jak coś chcesz to nie obrażaj. Odmawiam pomocy.

**Comment by Playerrrrrrrrrr** [comment]
EHKEM raczej sama a nie sam i wgl to pozdro yt niem bo ogólnie pokazuję
jacy są wredni ludzię tu więc nom ;-; I ogólnie to się wypchaj bo mogę
sobie kupić minecraft i mam dużą zniżkę w tym sklepie bo mnie lubiom . Ello
Karakanie ;p

pon., 8 cze 2020 o 12:49 LONGACAT <notifications@github.com> napisał(a):

**Comment by Playerrrrrrrrrr** [comment]
ESSAAAAAAAA

pon., 8 cze 2020 o 12:49 LONGACAT <notifications@github.com> napisał(a):

**Comment by Playerrrrrrrrrr** [comment]
ESSSSAAAA KURWO

pon., 8 cze 2020 o 17:47 __ oliva __ <falkowiczoliwia@gmail.com> napisał(a):

**Comment by Indexerrowaty** [comment]
Nie żeby coś ale my nie jesteśmy do Ciebie wrogo nastawieni.
Po prostu potrzebujemy więcej informacji aby Ci pomóc.
Samo napisanie, że Ci nie działa nic nam nie da.
Dlaczego? Nie wiemy co jest przyczyną tego, że Minecraft nie chce Ci się odpalić. Do tego potrzebujemy crashlogu/treści błędu.

**Comment by Indexerrowaty** [comment]
Poza tym przepraszam za tamto
> Usuń C:\\WINDOWS
wtedy myślałem, że to troll.

**Comment by Playerrrrrrrrrr** [comment]
Wysłałam wam screena idioto ;-;

pon., 8 cze 2020 o 19:42 Dawid <notifications@github.com> napisał(a):

**Comment by Indexerrowaty** [comment]
No tylko, że go nie widać.
Wrzuć na imgur czy coś.

**Comment by Playerrrrrrrrrr** [comment]
[image: image.png]


pon., 8 cze 2020 o 20:18 Dawid <notifications@github.com> napisał(a):

**Comment by Indexerrowaty** [comment]
![obraz](https://user-images.githubusercontent.com/39349444/84146541-20aad080-aa5c-11ea-8411-bbfb9e45700e.png)
No coś nie działa. Spróbuj wrzucić na [imgura](https://imgur.com/upload?beta).

**Comment by Playerrrrrrrrrr** [comment]
No poprusto pisze error i się nie włacza ;-;

wt., 9 cze 2020 o 14:19 Dawid <notifications@github.com> napisał(a):

**Comment by Indexerrowaty** [comment]
Tylko i wyłącznie pisze error?

**Comment by Playerrrrrrrrrr** [comment]
nom

wt., 9 cze 2020 o 15:08 Dawid <notifications@github.com> napisał(a):

**Comment by Indexerrowaty** [comment]
A w launcherze nie pokazuje nic? (dziennik gry czy coś)

**Comment by Playerrrrrrrrrr** [comment]
nie

wt., 9 cze 2020 o 21:20 Dawid <notifications@github.com> napisał(a):

**Comment by Indexerrowaty** [comment]
A zrób screenshota dziennika gry po włączeniu gry.

**Comment by Playerrrrrrrrrr** [comment]
Error: Could not find or load main class cpw.mods.modlauncher.Launcher. To
jest jedyne co pisze i się nie włącza nic

wt., 9 cze 2020 o 23:19 Dawid <notifications@github.com> napisał(a):

**Comment by Playerrrrrrrrrr** [comment]
Jestem downem lekkim ,okej ;-;

śr., 10 cze 2020 o 10:31 __ oliva __ <falkowiczoliwia@gmail.com> napisał(a):
