### ISSUE TITLE
I can't set more than 512mb/1gb RAM in SkLauncher also i have 16 gb of ram to use so i don't know why it happens

### ISSUE THREAD

**Issue by CryptonX15** [skmedix/SKlauncher#303]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by LONGACAT** [comment]
Install java 64-bit
