### ISSUE TITLE
30 GB is not enough to play Minecraft?

### ISSUE THREAD

**Issue by Ksawi999** [skmedix/SKlauncher#304]
I have left **30 GB** memory on my **C disk**, but why **Java** is **out of memory**? I tried to copy the Java folder to **D disk** (I have 700 GB on it) and manage that in Java but I must do that **every launch of computer**. When I open Minecraft even it **crashes** and in **crash report** there is: "_java.lang.OutOfMemoryError_": [crash-2020-06-08_10.30.00-client.txt](https://github.com/skmedix/SKlauncher/files/4744759/crash-2020-06-08_10.30.00-client.txt)
**Can I make that work better?**

What I did to play Minecraft:
![Java problem](https://user-images.githubusercontent.com/66205430/83999604-59b34a00-a963-11ea-92e9-95d37d9ed5ed.png)
It (in my opinion) works but I must do this every launch of computer (sometimes more often).

- OS: Windows 10
- Java version: Version 8 Update 251 (build 1.8.0_251-b08)

**Comment by Indexerrowaty** [comment]
Memory in this situation means RAM memory.
Allocate more ram to minecraft.

**Comment by Ksawi999** [comment]
> 
> 
> Memory in this situation means RAM memory.
> Allocate more ram to minecraft.

Thank you for help, but how to allocate more RAM memory? (I have gaming computer and that can't be problem to allocate more RAM memory)

**Comment by Indexerrowaty** [comment]
Right click on any profile in sklauncher you want. Then click edit profile. Then go to advanced settings and there allocate to minecraft as much ram as you want.

**Comment by Ksawi999** [comment]
Thanks but I have 1GB ram and I can't allocate more :/

**Comment by Indexerrowaty** [comment]
This means that you have 32-bit Java installed on your computer.
Install 64-bit Java. Don't forget to uninstall 32-bit Java.

**Comment by Ksawi999** [comment]
Thanks

**Comment by Ksawi999** [comment]
Why I can't have 32-bit and 64-bit Java?

**Comment by Indexerrowaty** [comment]
Because sometimes launcher uses 32-bit java instead of 64-bit java.

**Comment by Ksawi999** [comment]
Ok, thanks

**Comment by Indexerrowaty** [comment]
No problem :b

If you would ever need help in the future you can join our [Discord server](https://discord.gg/BdCcpDZ).
