### ISSUE TITLE
The game won't start

### ISSUE THREAD

**Issue by JustADude420** [skmedix/SKlauncher#307]
Minecraft won't even start at all after i click it for 2 times it loads nothing.

**To Reproduce**
1. Open up 'SKLuancher Beta'
2. Click on 'Start'
3. Wait a little until it completes loading
4. See the results

**Expected behavior**
It should start even if I wait a couple of minutes it won't start

- OS: Windows 10, SkLauncher Beta]
 - Java Version: ??
 - Launcher Version: Beta ( I think... )

**Comment by Indexerrowaty** [comment]
Is it showing anything at launcher?

**Comment by berkkrkc09** [comment]
I think they are talking about this screenshot
![javaw_BpaZcxnVWc](https://user-images.githubusercontent.com/57318309/85773898-00029c00-b727-11ea-869d-accdb84c7fa5.png)

**Comment by Indexerrowaty** [comment]
https://cdn.discordapp.com/attachments/7250275616663207976/725778369433829397/sklauncher-fx.jar
Put this inside .minecraft folder and try again. @berkkrkc09

**Comment by berkkrkc09** [comment]
I tried but unfortunately nothing changed.

**Comment by Indexerrowaty** [comment]
nah just put it into .minecraft

**Comment by berkkrkc09** [comment]
I tried launching it just before your answer and it seems to magically working now.

**Comment by Indexerrowaty** [comment]
Good to hear that.
Have fun playing Minecraft with SKlauncher.

**Comment by nikitk567** [comment]
I have the same problem, but the link is not working.

**Comment by Indexerrowaty** [comment]
@nikitk567 https://anonfiles.com/rfMbY3Nfo2/sklauncher-fx_jar
