### ISSUE TITLE
erorr po uruchomieniu gry

### ISSUE THREAD

**Issue by hajscker** [skmedix/SKlauncher#309]
po uruchomieniu gry natychmiastowo się zamyka i na lancher wyskakuje erorr i nie wiem co z robić na każdym nie działa może od sklancher otrzymam odpowiedź

**Comment by LONGACAT** [comment]
Jaki error? Skopiuj tekst lub wrzuć screenshota

**Comment by tochawariacie** [comment]
mam ten sam problem i wyświetla się to (0) : fatal error C9008: out of memory - malloc failed
Cg compiler terminated due to fatal errorAL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Indexerrowaty** [comment]
@tochawariacie przydziel więcej ramu do minecrafta.

**Comment by tochawariacie** [comment]
Ok dzięki

pt., 17 lip 2020, 01:54 użytkownik Dawid <notifications@github.com> napisał:
