### ISSUE TITLE
La skin no funciona en 1.16 pre7

### ISSUE THREAD

**Issue by Angelo5001** [skmedix/SKlauncher#310]
la skin me aparece actualizada en la pagina web, y tambien en el lanzador pero cuando ingreso a mi mundo me aparece la skin por defecto de Alex. estoy jugando la version 1.16 pre7

**Comment by skmedix** [comment]
Confirmed, we'll try to fix this before stable release of 1.16

**Comment by skmedix** [comment]
Fixed!

**Comment by Angelo5001** [comment]
Ya está arregla muchas gracias, ya me aparece la skin son los mejores a
todos dar ustedes.
