### ISSUE TITLE
Add more RAM functionality

### ISSUE THREAD

**Issue by Rocker9837** [skmedix/SKlauncher#313]
Hi! I have been using SKLauncher for a few weeks now and I've been noticing that my game says it doesn't have enough allocated ram to operate. I seen the max RAM usage tab in the advanced settings menu and I am only able to allocate 1GB of RAM into my PC. I have 4GBs of RAM and can play Minecraft with 2-3 GBs of RAM comfortably using the default Minecraft Launcher for the latest versions. I suggest putting a slider for max RAM usage and make it so you can go from 2GB of RAM to 8 gigs or something like that because I cant even RUN 1.16 with a RESOURCE PACK let alone the actual version itself... I have been using the normal Minecraft Launcher for things like:
*Adding resource packs for 1.13 and up
*Using Optifine for versions 1.13 and up
*Playing 1.16 AS A WHOLE

So I would appreciate it if you would take the time and effort to fix this problem and read this issue because it has taken a lot of time for me to type this and my fingers are really cold right now XD. But please fix this problem because its just making it frustrating for me to play Minecraft with your launcher. On the bright side I can play 1.8 and lower at max settings with Optifine and Texture packs so whatever is going on isn't my PC performance because its fine. Thanks! :D

**Comment by dderpen** [comment]
try installing java 64 bit that should let you use more than 1gb of ram in skl

**Comment by Rocker9837** [comment]
THANK YOU UR DA BESTTTT
