### ISSUE TITLE
Game crash while playing

### ISSUE THREAD

**Issue by Miella12** [skmedix/SKlauncher#315]
The game crashes while I am playing minecraft, sometimes it works for 30 minutes, other times can work for 1 hour or more, but it still crashes at a certain point.
I expected not to happen, after an explanation why it crashes
I think the problem is launcher related, but I don't know certainly

**Environment (please complete the following information):**
 - Windows 10
 - Java Version: 8u251
 - Launcher Version: 3.0-8d59ece

![Screenshot_1](https://user-images.githubusercontent.com/67598895/86033237-ea4bea00-ba38-11ea-82bd-583c196570d1.png)
![Screenshot_2](https://user-images.githubusercontent.com/67598895/86033303-0b143f80-ba39-11ea-8842-5825c165972e.png)

**Comment by LONGACAT** [comment]
It is a bug in the Intel driver, something that is impossible to fix.
