### ISSUE TITLE
mi skin no es la que escogi

### ISSUE THREAD

**Issue by Angelo5001** [skmedix/SKlauncher#319]
en la pagina de sklauncher aparece mi skin que yo escogi, pero cuando entro a un servidor me aparece una skin antigua que usaba hace tiempo.

**Comment by Indexerrowaty** [comment]
> Skins are DISABLED due to high traffic and WILL STAY DISABLED until further notice.

**Comment by Angelo5001** [comment]
> > Las máscaras están DESACTIVADAS debido al alto tráfico y PERMANECERÁN DESACTIVADAS hasta nuevo aviso.

en un mundo solitario y en mi servidor privado aparece la skin que escogi, pero en servidores que no son mios aparece la antigua.

**Comment by Indexerrowaty** [comment]
🤔 maybe your skin is still processing in our servers
