### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Astrek100yt** [skmedix/SKlauncher#320]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Astrek100yt** [comment]
Hello, I am a Astrek100yt player and I have a problem. When I play server or with friends, they don't see my skin and I can see it. I am asking you to solve the problem and tell me what happened.  Best wishes Astrek100yt

**Comment by Indexerrowaty** [comment]
Skins will be fixed this month.

**Comment by Indexerrowaty** [comment]
It should be fixed now.
