### ISSUE TITLE
Does SKlauncher not update my username change? 

### ISSUE THREAD

**Issue by nicolasmerlo** [skmedix/SKlauncher#327]
I changed my SKmedix username, when I log into SKlauncher it won't let me in. It says "Please use your email address" but when I try to enter as indicated it cannot find my account. I can log into the website normally, my password is not the problem, the launcher does not recognize my email and name.
![1](https://user-images.githubusercontent.com/68680842/88258653-0426c880-cc97-11ea-91fb-3401d863053e.png)
![2](https://user-images.githubusercontent.com/68680842/88258656-0557f580-cc97-11ea-9c3a-ee0bbcb47bc6.png)
![3](https://user-images.githubusercontent.com/68680842/88259181-2cfb8d80-cc98-11ea-81d0-2009527711ad.png)

**Comment by Indexerrowaty** [comment]
Tick Offline (Desconectando) checkbox then type your new nickname and click login.
