### ISSUE TITLE
Skin won't update for some reason?

### ISSUE THREAD

**Issue by Snikerdoodles** [skmedix/SKlauncher#328]
**Describe the bug**
It's as the title says. I changed my skin on the customization webpage but it doesn't update in-game for me. Other fellow SKlauncher users are able to see my skin updated (according to some friends I play with on a server), but it still remains the same on my screen.

**To Reproduce**
1. Go on the customization webpage and change the skin.
2. Log in offline using the username used in the customization and play the game.

**Expected behavior**
The skin will remain the same as the previous one, though other users in multiplayer are able to see my skin.

I'm still figuring out whether this is an issue on the website or just me, because for a while my skin has shown to be updated but then after it reverts back to the previous one. It's annoying and I want to see my skin updated but it sucks if only other users are able to see it and not me.

**Comment by Indexerrowaty** [comment]
It's probably cache related issue that has been fixed some time ago.
Are you still experiencing this issue?
