### ISSUE TITLE
When I first join the minecraft server, it started lagging then after i break 1 block it crashed 

### ISSUE THREAD

**Issue by ItIsAnnabel** [skmedix/SKlauncher#333]
It first lagged then it crashed :<
Please help fix it

**Comment by Indexerrowaty** [comment]
Crashlog?

**Comment by Ninteos** [comment]
That means you need to allow more ram or upgrade your pc

y

**Comment by pepefog** [comment]
I have the same problem and when I try to increase the RAM it says the max is 1GB (My pc has 8)

**Comment by Indexerrowaty** [comment]
> I have the same problem and when I try to increase the RAM it says the max is 1GB (My pc has 8)

Install 64-bit Java
