### ISSUE TITLE
Skin won't update (even in the new update of the launcher & site)

### ISSUE THREAD

**Issue by Snikerdoodles** [skmedix/SKlauncher#334]
**Describe the bug**
So my skin prior to the new updates (where the slim models were still bugged and capes were not yet available) is being shown to me when I click the "slim" checkbox. I have no way of resetting or removing the custom skin on the slim model, and every time I input an Alex model skin (or even put Steve model skins with the slim option unchecked) and click "Save Changes", it will always reset to my old skin.

**To Reproduce**
1. Go to the customization page or the "profile manager" on the website
2. Place any skin and cape in (check the "slim model" if the skin uses the Alex model)
3. Click "Save Changes"

**Expected behavior**
After saving changes, the skin will just revert back to how it was.

**Screenshots**
https://snikertotheduece.s-ul.eu/F0hTgIBi <- Inputting the desired skin, cape, and model

https://snikertotheduece.s-ul.eu/Gb8nJ3f1 <- What happens after saving changes

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 79.0

**Comment by Indexerrowaty** [comment]
It's cache fault. You have to wait until cache expires.
