### ISSUE TITLE
Infinite downloading

### ISSUE THREAD

**Issue by iRealistiX** [skmedix/SKlauncher#335]
**Describe the bug**
Downloading librairies is broken, when I want to launch a already installed version, sometimes it downloads "Librairies" it is frozen on downloading one.
Do not say it is my connection i got 40 Mbps in download/upload

**To Reproduce**
Nothing, random bug

**Expected behavior**
Downloading freezes

**Screenshots**
Some screenshots
![image](https://user-images.githubusercontent.com/67875888/89398433-05310e80-d709-11ea-9523-45e0dac102a5.png)

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: Windows 10/Version 1809
 - Java Version: 8u261
 - Launcher Version: 3.0-58a20df

**Comment by Indexerrowaty** [comment]
Do you still experience this bug?
If yes then please send **`sklauncher.log`** from `%AppData%\.minecraft\sklauncher\`.

**Comment by iRealistiX** [comment]
Soory bit i'm now premium,
bye
