### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by DarkNemerklid** [skmedix/SKlauncher#336]
i have a problem to log in whe i tray to log in to the luncher i just cant it show me incorect pasword and i can log in to the weebsite but i dont know why i can't on luncher

**Comment by DarkNemerklid** [comment]
sorry for my disable english skills

**Comment by DarkNemerklid** [comment]
tak właściwie to ja z polski jestem jak jakiś polako mako potrafi mi pomuc to BłAgaM!! ja nie mogę sięzaogować na lunchera mimo że na stronie od SKluncher jużtak i nie iwem o co choedzi nie wiem cz ja jestem upośledzony czy jak bo mi wyświetla łędne hasło albo login

**Comment by Indexerrowaty** [comment]
Zaznacz opcję offline i wpisz swój nick. Wtedy kliknij log in.
