### ISSUE TITLE
Try to load up 1.16.2? Get your profiles removed.

### ISSUE THREAD

**Issue by JakeyAnimates** [skmedix/SKlauncher#338]
The new 1.16.2 update just dropped a couple of minutes ago and I wanted to see what was new in the update. But because of my specs, it crashed. I boot up the launcher again, and all my profiles, servers and more specifically, WORLDS are gone out of thin air. I don't know if this a glitch or some sort of thing with my PC, but this isn't good.

**Comment by skmedix** [comment]
Pretty sure they are in the different directory `.minecraft/profiles/<name of the profile>`
