### ISSUE TITLE
It says "Oops! An Error Occured" everytime I pressed the link to get a skin for my account

### ISSUE THREAD

**Issue by Ohdeathyay** [skmedix/SKlauncher#341]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Indexerrowaty** [comment]
> I pressed the link to get a skin for my account

On which link you clicked to get a skin?
