### ISSUE TITLE
always crashes

### ISSUE THREAD

**Issue by MrCroak** [skmedix/SKlauncher#343]
crash
When i play with some mods on minecraft and i start a new word,
 at first everything is good but when i start to break some blocks or a mob attacks me the game always crashes. 
I was plaing with only 1 mod it was using only about 200 mb ram i even set max ram to  7,5 gb ram but it still was breaking,
when i read the game log it said "Can't keep up! Did the system time change, or is the server overloaded? Running 3960ms behind, skipping 79 tick(s)" i don't think its something is wrong with my laptop because i just got a new one and when my brother tried some other mods (a LOT more more) and it didn't crash even once idk what's going on someone please help

**Comment by Indexerrowaty** [comment]
Please send crashlog so that we can tell you what's wrong.

**Comment by MrCroak** [comment]
my brother fixed it thx, and apparently the game was freezing soo there was no crash log
