### ISSUE TITLE
Cape size is too big

### ISSUE THREAD

**Issue by NeoGamer760** [skmedix/SKlauncher#344]
**Describe the bug**
When i try to put on a cape it tells me to resize it ,when i do the cape looks too big ,even ingame the cape is still to big.

**To Reproduce**
1. Go to customization
2. Click on Choose cape file
3. Resize the cape to the size it tells you to
4. Put on the cape
5. See error

**Expected behavior**
I expected the cape to look normal but it looks too big in the customisation and ingame.

**Screenshots**
https://imgur.com/gallery/EMjhFS7

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS:Windows 10
 - Browser:Chrome 84

**Comment by skmedix** [comment]
Hi, use this template for your skin (you'll probably need to redraw it)
![cape (1)](https://user-images.githubusercontent.com/3246162/90339385-b892e080-dff0-11ea-85df-a5488d53296a.png)
