### ISSUE TITLE
Problems connection on LAN

### ISSUE THREAD

**Issue by MetalMaster999** [skmedix/SKlauncher#347]
Me and my friend both use SKLauncher as our Minecraft source. When we try to play together on LAN it never works. it always says Failed to Login : Invalid session (Try restarting your game). It doesn't matter which computer hosts the session we always get the same error. The weird thing is whenever I play with a friend who as the official licenced Minecraft playing on LAn works. Any solutions??????

**Comment by Indexerrowaty** [comment]
Open minecraft without internet connection then open your world and start a LAN server.
Then connect again to your WiFi. This should do it.
