### ISSUE TITLE
Minecraft crashing from joining a server or a singleplayer world

### ISSUE THREAD

**Issue by Kingzoid** [skmedix/SKlauncher#348]
**Describe the bug**
when I join a singleplayer I made it crashs and it crashs when i want to play a server like skykingdoms and it does not let me in hypixel.

**To Reproduce**
1. Go to any minecraft server
2. Click on it
3. and crashs..'
4. See error in the launcher

**Expected behavior**
The things I described

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Indexerrowaty** [comment]
The server that you trying to join is in online-mode (premium) so you can't join it.
(If you're an admin of the server, change the option online-mode to false in file server.properties)
