### ISSUE TITLE
This some weird bug...

### ISSUE THREAD

**Issue by camelCase-dumb** [skmedix/SKlauncher#349]
**Describe the bug**
I can't put it in words but I have a screenshot.

**To Reproduce**
1. Just open the launcher and you will see it right away.

**Expected behavior**
The window is in a weird state.

**Screenshots**
![weirdbug](https://user-images.githubusercontent.com/56781329/92322946-303fb280-f067-11ea-8751-4f77b87c1c26.png)

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: Arch Linux 5.8.5-arch1-1 
 - Java Version: 1.8.0_261-b12
 - Launcher Version: 3-beta.16 (I took it from a filename)

**Comment by Indexerrowaty** [comment]
Happens on macOS too. But it looks like this:
![obraz](https://user-images.githubusercontent.com/39349444/92323264-990f3680-f037-11ea-812b-706522d6104b.png)

**Comment by LONGACAT** [comment]
That is a JavaFX bug, sadly there isn't anything we can do right now to fix it. It does not affect the functionality of the launcher in any way

**Comment by camelCase-dumb** [comment]
It's okay it doesn't bother me anyway.
Thanks for letting us know though.
