### ISSUE TITLE
The new launcher doesnt allow me to change the allocated RAM.

### ISSUE THREAD

**Issue by mamiopro** [skmedix/SKlauncher#351]
To Reproduce:
1. Open the new launcher
2. Choose a profile
3. Open "Edit Profile"
4. Go to the advanced settings
5. Change the allocated RAM to anything

Expected behavior:
The profile opens and works, but if you use forge to see the memory usage at opening, it is stuck at max. 4 GB of ram and you cant change it no matter what you try.

I tried reinstalling everything you will probably say, nothing changed.

Better explanataion: I changed the allocated RAM to 7.5 gigs. I open the game (it is modded heavily but this bug appears on comlete vanilla too). Even if the allocated RAM is 7.5 gigs, the game only uses 4 gigs. When i allocate 3 gigs to see if there is something with accidental 32x bit java but the game said it is 4 gigs again. I looked on the internet but i didnt saw anything like that. No i dont get a crash report, no logs, anything.
 
Idk if im not supposed to play modded on this launcher but i did find a way. I cant play the modpack with 4 gigs, it doesnt allow me because it is a huge modpack. 

Note: I was able to play modded with no problem until the 3rd version of the launcher came. Ill try to use the old one but idk if it will let me.

Environment:
 - OS: Windows 10 Pro
 - Java Version: Always up to date
 - Launcher Version: Always up to date
Sorry if there is bad sentences, English is my second language.

**Comment by mamiopro** [comment]
Edit: I i couldnt try the old launcher because it doesnt open.

**Comment by skmedix** [comment]
Update released, try again

**Comment by mamiopro** [comment]
Tried again, nothing changed :(

**Comment by mamiopro** [comment]
AHA!
Works now! Thank you!
