### ISSUE TITLE
ERROR The file is too large (164.85 kB). Allowed maximum size is 25 kB. ERROR The image width is too big (1024px). Allowed maximum width is 64px when choosing cape

### ISSUE THREAD

**Issue by TechPointCh** [skmedix/SKlauncher#353]
When I upload a custom Optifine Cape or another cape which is not a minecon one, This error message pops out, please fix this:

ERROR The file is too large (164.85 kB). Allowed maximum size is 25 kB.
ERROR The image width is too big (1024px). Allowed maximum width is 64px

**Comment by Indexerrowaty** [comment]
Send cape here.

**Comment by WinterNya** [comment]
The cape is sized incorrectly. Please use the templates pack when drawing capes.

**Comment by TechPointCh** [comment]
But optifine capes?

**Comment by TechPointCh** [comment]
Why is Custom Optifine capes not working?

**Comment by Indexerrowaty** [comment]
Cape should look like this:
![h.png](https://user-images.githubusercontent.com/39349444/93473082-dd32ee80-f8f5-11ea-94f7-dd705b1cff93.png)

**Comment by TechPointCh** [comment]
yes, It's the same format that the Optifine cape that I used has

**Comment by TechPointCh** [comment]
It is the same format

**Comment by Indexerrowaty** [comment]
Ok then rescale it to 64px x 32px.

**Comment by Indexerrowaty** [comment]
If you want to I can do that for you. Just send that cape you are trying to set there.

**Comment by TechPointCh** [comment]
okay

**Comment by TechPointCh** [comment]
https://cdn.discordapp.com/attachments/750551010346401832/756128722498879628/latros_masterpiece_Lunar_Badlion.png

**Comment by TechPointCh** [comment]
That's the image

**Comment by WinterNya** [comment]
Threre is no way this can be rescaled to 64x32, it is drawn in too high resolution.

**Comment by TechPointCh** [comment]
Then is one please https://cdn.discordapp.com/attachments/750551010346401832/756138329980010606/Custom_OptFine_Cape_1598678485.png

**Comment by Indexerrowaty** [comment]
Done
![Custom_OptFine_Cape_1598678485](https://user-images.githubusercontent.com/39349444/93474911-4ae01a00-f8f8-11ea-92d1-3f9aea1051c9.png)

**Comment by Indexerrowaty** [comment]
@TechPointCh

**Comment by TechPointCh** [comment]
Thank you!

**Comment by Indexerrowaty** [comment]
No problem ;)
