### ISSUE TITLE
Skin and cape is not showing up on servers

### ISSUE THREAD

**Issue by DarkmythicYT** [skmedix/SKlauncher#354]
My skins and capes are not showing up on pvp and bedwars servers but it shows up on my server
This it what it shows on other servers
![received_374564063712681](https://user-images.githubusercontent.com/71612913/93724708-2af07500-fbdc-11ea-8128-3c271a553c9c.png)
And i also play offline mode

Please help...
Thanks!!!

**Comment by Indexerrowaty** [comment]
It's because someone has a premium account which nickname is exactly like yours.
