### ISSUE TITLE
Infinite Loading....

### ISSUE THREAD

**Issue by JakeyAnimates** [skmedix/SKlauncher#355]
I cant load into Minecraft, no matter how much I try.
![Capture](https://user-images.githubusercontent.com/69531542/94571154-90d99e00-0267-11eb-80ef-115a82dc5c4c.PNG)

**Comment by Indexerrowaty** [comment]
Please send launcher log

**Comment by JakeyAnimates** [comment]
![image](https://user-images.githubusercontent.com/69531542/94590368-79f27600-027e-11eb-9f8d-3da9313dfafd.png)
this?

**Comment by Indexerrowaty** [comment]
Nah. Drag and drop this file: `%appdata%\.minecraft\sklauncher\sklauncher.log`

**Comment by JakeyAnimates** [comment]
[Uploading sklauncher.log…]()

**Comment by JakeyAnimates** [comment]
[sklauncher.log](https://github.com/skmedix/SKlauncher/files/5301462/sklauncher.log)

**Comment by Indexerrowaty** [comment]
Please rerun the launcher and try again an update with a fix just git released. Please close the issue if this resolved your problem.
