### ISSUE TITLE
Launcher nie chce się wyłączyć... 

### ISSUE THREAD

**Issue by Nigia** [skmedix/SKlauncher#356]
Chce przenieść plik na pulpit, ale pisze, że najpierw muszę wyłączyć Launcher..... Nie wiem co zrobic bo probowalem roznych sposobów.POMOCY!!!!!!!

**Comment by Indexerrowaty** [comment]
Kliknij X w prawym górnym logu i przenieś plik .jar lub .exe SKlaunchera.
