### ISSUE TITLE
Sklauncher skin

### ISSUE THREAD

**Issue by DragsterzzYT** [skmedix/SKlauncher#357]
My skin is not coming plese tell me what to do

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Indexerrowaty** [comment]
Make sure that `Compatibility mode` is not enabled.

**Comment by CopiPL64** [comment]
i have this same problem and i don't know how to turn  this off

**Comment by Indexerrowaty** [comment]
Right click on a profile you are using then click edit profile and turn off compatibility mode.

**Comment by CopiPL64** [comment]
i can't see edit

**Comment by Indexerrowaty** [comment]
Screenshot what appears on your screen after you right-click a profile.

**Comment by CopiPL64** [comment]
but on google or in app?

**Comment by CopiPL64** [comment]
i know whats the problem i didn't buyed minecraft and i put my nickname in google but in app i have plyer

**Comment by Indexerrowaty** [comment]
In SKlauncher.

**Comment by Indexerrowaty** [comment]
Closed due to not enough information about this problem and inactivity.
