### ISSUE TITLE
Ability to install modpacks through SKlauncher.

### ISSUE THREAD

**Issue by camelCase-dumb** [skmedix/SKlauncher#358]
**Is your feature request related to a problem? Please describe.**
I have so much minecraft launchers in my desktop (Modpacks launcher) and I want SKlauncher would be my main.

**Describe the solution you'd like**
Installing modpacks from curseforge (zip files).

**Describe alternatives you've considered**
Downloading mods one by one, it's pretty hard and really time consuming and lots of efforts.

**Additional context**
This is gonna be amazing if this feature is added.
And I would happily delete my other modpack launchers, and SKlauncher as my main.
I hope this is possible...

**Comment by WinterNya** [comment]
This somewhat works, Windows-only, requires to have .NET Core installed, and you need to install and set the game version manually. https://github.com/WinterNya/Modpack-Installer

**Comment by camelCase-dumb** [comment]
Awesome but somehow I'm on linux, but this is great opportunity to test it if this installer is working through wine.

**Comment by WinterNya** [comment]
All it could possibly do then is create a folder with the files you would copy to ~/.minecraft/profiles. It looks for %appdata%/.minecraft and if that is missing it just doesn't copy anything and leaves the downloaded files next to the executable.

**Comment by camelCase-dumb** [comment]
I saw the .cs file and I think i can rewrite it to nodejs, but I don't understand some parts of your code 'cause there is no comments.

**Comment by WinterNya** [comment]
Of course there is no comments, this was just a quick hack for myself so I wouldn't need to use CMPDL (which you should check out by the way, it's crossplatform), I never even intended to publish it.
