### ISSUE TITLE
I have a problem. I can't launch minecraft please help me fix it

### ISSUE THREAD

**Issue by MrArtYT** [skmedix/SKlauncher#361]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Indexerrowaty** [comment]
You didn't even specify the error that appears on your screen after launching Minecraft. Please screenshot that error and send it here.

**Comment by MrArtYT** [comment]
[image: Screenshot (25).png]

**Comment by Indexerrowaty** [comment]
Try attaching that screenshot again because I can't see it.
