### ISSUE TITLE
When I run SKlauncher-

### ISSUE THREAD

**Issue by Natalia123UvU** [skmedix/SKlauncher#362]
When I click play minecraft he won't turn on

1. Go to 'Sklauncher'
2. Click on 'play'
3. And see, he won't turn on

 - OS: windows 7
 - Java Version: jre-8u271
 - Launcher Version: 3.0-3285da3

 - OS: windows 7
 - Browser: Opera GX

**Comment by Indexerrowaty** [comment]
Download .jar (linux version) of SKlauncher from [here](https://skmedix.pl/sklauncher/downloads).
