### ISSUE TITLE
I can't Run Sklauncher.exe to install the launcher Pls help

### ISSUE THREAD

**Issue by Lolguy8321** [skmedix/SKlauncher#363]
i downloaded the setup and run it and nothing happens hellppp btw i have win 10

**Comment by Indexerrowaty** [comment]
There are 2 ways to fix this issue.
1. Download .jar (Linux) version of SKlauncher.
Or
2. Download and install Oracle Java 8. https://java.com/en/download/manual.jsp

**Comment by Lolguy8321** [comment]
Still dosen't work can i know your pc windows version when you tested the launcher?
