### ISSUE TITLE
Can't run sklauncher.exe to install launcher pls help also tried what indexerrowaty said.

### ISSUE THREAD

**Issue by Lolguy8321** [skmedix/SKlauncher#364]
Hello again i tried what you said but it did not work can i know your windows version you are using??

**Comment by Indexerrowaty** [comment]
Im not using Windows.
Did you try opening .jar version of the launcher?

**Comment by Lolguy8321** [comment]
Yes i did.

**Comment by Indexerrowaty** [comment]
Still nothing appeared on your screen?

**Comment by Lolguy8321** [comment]
Nope.

**Comment by Lolguy8321** [comment]
And also i checked task manager and it showed nothing.

**Comment by Lolguy8321** [comment]
But its alright tho i am using multimc i wanted to use sklauncher for modpacks and because it looked cool but its not working thx for your help tho!! :D

**Comment by Lolguy8321** [comment]
Hi! thanks for your advice i fixed it by using java yay thanksssssssss
