### ISSUE TITLE
Minecraft closes after a few seconds

### ISSUE THREAD

**Issue by JuanluTocayo** [skmedix/SKlauncher#367]
**Describe the bug**
When I enter a world after a few seconds the game starts, all closes and the sklauncher writes an error
**To Reproduce**
1. Click on PLAY on the launcher
2. Minecraft starts
3. Enter the singleplayer menu
4. Click the > on an already created world or create a new world
5. Wait until the world charges
6. Start playing
7. Either you are moving, doing things, stopped in place or in the menu, the game closes and the launcher sends this:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x528ada83, pid=2208, tid=0x000026a0
#
# JRE version: Java(TM) SE Runtime Environment (8.0_231-b11) (build 1.8.0_231-b11)
# Java VM: Java HotSpot(TM) Client VM (25.231-b11 mixed mode windows-x86 )
# Problematic frame:
# C  [ig11icd32.dll+0x1bda83]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\corre\AppData\Roaming\.minecraft\hs_err_pid2208.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
[error occurred during error reporting , id 0xc0000005]

**Comment by Indexerrowaty** [comment]
Update your drivers.
