### ISSUE TITLE
I can't find the version I downloaded.

### ISSUE THREAD

**Issue by Lezulius** [skmedix/SKlauncher#368]
**Describe the bug**
The launcher deleted the version.

**To Reproduce**
1. I downloaded Hyperium 1.8.9.
2. I opened SKLauncher.
3. A new profile was created named Hyperium 1.8.9.
4. It was Version 1.16.4
5. I tried to change it but it launched by itself.
6. I closed it and opened SKLauncher again.
7. And the version was gone I couldn't click on the profile again

**Expected behavior**
The version disappeared all of a sudden.

**Screenshots**
![Screenshot (13)](https://user-images.githubusercontent.com/75461327/101115228-f35f6980-361d-11eb-8830-3989cd66325d.png)

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Java Version: [Java 8u271]
 - Launcher Version: [3.0-3285da3]

**Comment by Indexerrowaty** [comment]
Click on that profile and run the game.
![obraz](https://user-images.githubusercontent.com/39349444/101172253-3da61200-3641-11eb-8538-7d73628fc311.png)

**Comment by Lezulius** [comment]
> Click on that profile and run the game.
> ![obraz](https://user-images.githubusercontent.com/39349444/101172253-3da61200-3641-11eb-8538-7d73628fc311.png)

thats what i have been clicking on
