### ISSUE TITLE
Nie mogę włączyć Minecrafta

### ISSUE THREAD

**Issue by ilkirt123441** [skmedix/SKlauncher#369]
Jak klikam przycisk Graj to nie włącza mi się czekałem nawet 1 godz prosze to naprawić

**Comment by Indexerrowaty** [comment]
Wyślij SKlauncher.log z `%appdata%\.minecraft\sklauncher\sklauncher.log`.

**Comment by kaczka100** [comment]
jak klikam graj to po kilku sek pisze mi uruchamianie i sie nie włańcza

**Comment by Indexerrowaty** [comment]
A weź ustaw w ustawieniach profilu aby launcher pozostawał włączony podczas gdy gra jest uruchomiona i wyślij crashlog który tam się pojawi.
