### ISSUE TITLE
Launcher Not Even Opening

### ISSUE THREAD

**Issue by Vly2915** [skmedix/SKlauncher#37]
When i try to open the launcher nothing happens, not even the cursor showing it's loading...
I tried to use both the 2.8 and the 3.0 version with the same result, and the same thing happens with other launchers, additionally opening as Administrators does nothing.
I have recently updated javato the latest version and remove the older ones.

**Comment by skmedix** [comment]
Try to use `java -version` in `cmd`. If that command fails, then your Java installation is broken.

**Comment by Vly2915** [comment]
Yep, that failed.
Thanks for the fast answer.
