### ISSUE TITLE
The launcher wont even open for me

### ISSUE THREAD

**Issue by BURGER64** [skmedix/SKlauncher#372]
when i try to open the launcher it just doesnt open, ever. i even downloaded the recomended java version in the download website but it just doesnt work. i tried reinstalling and other stuff but nothing happens. the launcher never opens. pls if someone can help me.

**Comment by Indexerrowaty** [comment]
Try downloading and running .jar (Linux) version of a launcher

**Comment by BURGER64** [comment]
> Try downloading and running .jar (Linux) version of a launcher

ok

**Comment by BURGER64** [comment]
oh my god

**Comment by BURGER64** [comment]
it worked!!!!!11

**Comment by BURGER64** [comment]
thx so much i really appreciate it

**Comment by Indexerrowaty** [comment]
No problem :D
Have fun playing Minecraft!
