### ISSUE TITLE
I updated the launcher and it does'nt want to open

### ISSUE THREAD

**Issue by Rathecke** [skmedix/SKlauncher#375]
i updated sklauncher to the newest version of it and now it does'nt want to open, all it does is make the mouse do the little loading thing but nothing happens

i use a windows 10
java version 8, update 271

**Comment by Indexerrowaty** [comment]
There are 2 ways to fix this issue.
1. Download .jar (Universal) version of SKlauncher.
Or
2. Download and install Oracle Java 8. https://java.com/en/download/manual.jsp
