### ISSUE TITLE
Skins not working for others in multiplayer

### ISSUE THREAD

**Issue by Jailbreak4Life** [skmedix/SKlauncher#376]
I was playing minecraft 1.16.4 with optifine installed using SKLauncher. My two other friends were using TLauncher. I could see my own skin and cape but my friends said that they see an Alex skin with no capes. And same was happening with me, I could not see my friends skin but Alex skins instead. I have turned off compatibility mode.

**Comment by spunkymonkey56** [comment]
Tlauncher skins only work if all clients are using Tlauncher,ask if they can migrate to Sklauncher :(

**Comment by spunkymonkey56** [comment]
i myself just had this problem lmfao

**Comment by Indexerrowaty** [comment]
People can only see your SKlauncher skin when they use SKlauncher too.
