### ISSUE TITLE
Sklauncher is Broken

### ISSUE THREAD

**Issue by HellexTRU** [skmedix/SKlauncher#377]
its keeps on saying "This application requires a Java Runtime Environment. Check "skmedix.pl/Sklauncher" 1.8.0_69 - 1.8.0_999" or something
and right after i downloaded the app it opened on my google (liberica) it wont open.
no matter how many times i clicked on it it wont open
i need help

**Comment by Indexerrowaty** [comment]
There are 2 ways to fix this issue.
1. Download .jar (Universal) version of SKlauncher.
Or
2. Download and install Oracle Java 8. https://java.com/en/download/manual.jsp

**Comment by HellexTRU** [comment]
the jar one worked. thanks

**Comment by Indexerrowaty** [comment]
No problem. Have fun playing Minecraft!
