### ISSUE TITLE
Launcher doesn't open

### ISSUE THREAD

**Issue by beryll-ops** [skmedix/SKlauncher#384]
I built new PC, installed all drivers and installed latest Java8. When I'm trying to open the launcher nothing happens.

 - OS: [ Windows 10 Pro]
 - Java Version: [8 latest]
 - Launcher Version: [Beta 3.0 17.2]

**Comment by Indexerrowaty** [comment]
There are 2 ways to fix this issue.
1. Download .jar (Universal) version of SKlauncher.
Or
2. Download and install Oracle Java 8. https://java.com/en/download/manual.jsp
