### ISSUE TITLE
SkLauncher Does not open after download, JDK8 Installed.

### ISSUE THREAD

**Issue by Shmubbi** [skmedix/SKlauncher#386]
After Installing The Launcher itself from the website, it shows the cursor loading for a few seconds then nothing happens. I have not installed The game before and I am using Liberica Full JDK 8. for Java.

To Reproduce
1.Download Launcher
2.Open Launcher
3.Does not show anything.

**Expected behavior**
Expected to open Launcher and prompt Username and password.

**Environment (please complete the following information):**
 - OS: Windows 10 20H2
 - Java Version: Liberica JDK 8 | 1.8.0_282
 - Launcher Version: SKlauncher 3.0 beta.17.2

**Comment by Indexerrowaty** [comment]
There are 2 ways to fix this issue.
1. Download .jar (Universal) version of SKlauncher.
Or
2. Download and install Oracle Java 8. https://java.com/en/download/manual.jsp
