### ISSUE TITLE
Launcher opening and closing

### ISSUE THREAD

**Issue by Kingowst** [skmedix/SKlauncher#389]
When I'm clicking the launcher everythings alright but then it closes and soon opens again then closes and opens. Could you fix that?

**Comment by Indexerrowaty** [comment]
Install this Java: https://java.com/en/download/manual.jsp

**Comment by Kingowst** [comment]
> Install this Java: https://java.com/en/download/manual.jsp

What should I do next? I downloaded it and put in .minecraft in %appdata%, still opening and closing

**Comment by Kingowst** [comment]
> Install this Java: https://java.com/en/download/manual.jsp

Oh and I forgot I got mods, It's just RLCraft and mileneire
