### ISSUE TITLE
Ram allocator

### ISSUE THREAD

**Issue by demonite87x** [skmedix/SKlauncher#395]
most of minecraft launcher (like tlauncher even the official launcher itself) has a ram allocator, my suggestion is that to add ram allocator like my pc has 6 gb and i want to allocate my ram to 3 and there is no button to do it so, i hope you can add that feature

**Comment by WinterNya** [comment]
Right click on a profile, edit profile, Advanded settings, there's a RAM usage dropdown. It sets automatically to half of your RAM.
