### ISSUE TITLE
"Required Restart" window is displayed in incorrect language

### ISSUE THREAD

**Issue by Greg-21** [skmedix/SKlauncher#54]
If the language of the launcher is set to e.g. English and you change it to e.g. Polish, and click "OK", the displayed window is in incorrect language (should be in English, but it's in Polish).

SKlauncher version: 3.0 Beta

Screenshot showing this issue:
![incorrect-language](https://user-images.githubusercontent.com/34160838/42562746-d8ac02bc-84fc-11e8-81cb-56412cd54490.png)

**Comment by skmedix** [comment]
Actually, not an issue. I thought if a user changed the language, why already don't give him info in a chosen language
