### ISSUE TITLE
Labels overlap other input fields

### ISSUE THREAD

**Issue by Greg-21** [skmedix/SKlauncher#55]
When you remove the text from the input field, it starts showing the label, which overlaps input fields that are above it. Furthermore, the "Profile Name" label "escapes" beyond the window.

I think you should rather increase spaces between input fields, instead of removing the labels completely. To be consistent with Material Design principles.

SKlauncher version: 3.0 Beta

Screenshot showing this issue:
![overlapping-labels](https://user-images.githubusercontent.com/34160838/42564500-37ca1e7e-8501-11e8-91cf-6cab5925d36e.png)

**Comment by skmedix** [comment]
**Fixed** in `3.0-ca4766a`
