### ISSUE TITLE
"x" is incorrectly positioned

### ISSUE THREAD

**Issue by Greg-21** [skmedix/SKlauncher#56]
The "x" between display resolution's width and height is centered neither vertically nor horizontally.

SKlauncher version: 3.0 Beta

Screenshot showing this issue:
![x-between-width-and-height](https://user-images.githubusercontent.com/34160838/42567430-003edb80-850a-11e8-8d64-8642e2143cd4.png)

See also: #57

**Comment by skmedix** [comment]
**Fixed** in `3.0-ca4766a`
