### ISSUE TITLE
Replace the "x" letter with the multiplication sign

### ISSUE THREAD

**Issue by Greg-21** [skmedix/SKlauncher#57]
The "x" letter between display resolution's width and height should be replaced with the multiplication
sign – `×`.

SKlauncher version: 3.0 Beta

Screenshot showing the "x" letter:
![x-between-width-and-height](https://user-images.githubusercontent.com/34160838/42567430-003edb80-850a-11e8-8d64-8642e2143cd4.png)

See also: #56

**Comment by skmedix** [comment]
**Changed** in `3.0-ca4766a`
