### ISSUE TITLE
Alex model based skin launching on Steve model

### ISSUE THREAD

**Issue by Kushimaru** [skmedix/SKlauncher#59]
My skin is based on Alex model. I set the player model for Alex in the Customization, but when i launch the game and enter into my world my skin is on Steve model. Does someone know how to fix it?

**Comment by skmedix** [comment]
Are you using 2.8 or 3.0?

**Comment by Kushimaru** [comment]
I'm using 2.8,  but not so long ago the skin worked properly

**Comment by skmedix** [comment]
Capes & skin models are supported since 3.0

**Comment by Kushimaru** [comment]
Ok, I understand. Thank you for help.:)
