### ISSUE TITLE
[Feature] Option to change accent color

### ISSUE THREAD

**Issue by D34D-514R** [skmedix/SKlauncher#61]
# O co chodzi?
Przyciski, linie, pola tekstowe itp. mają domyślnie kolor niebieski, ale dzięki wyborze koloru akcentu można byłoby zmienić ten kolor.

## Po co?
Wybór koloru akcentu może być dobry dla osób którzy wolą jakiś inny kolor niż niebieski np. zielony.

**Comment by CodeIndexer** [comment]
P.S: Wysłałem tutaj sugestię bo pisało na GitHubie, że tutaj też można sugestie dodawać.

**Comment by Waterrail** [comment]
Myślę, że wystarczy dodać nowy motyw. Głównie z takiego powodu, że ludzie nieraz mogą wybrać jakiś beznadziejny kolor, który nie będzie pasował.

**Comment by CodeIndexer** [comment]
No, właśnie myślę iż zestaw kolorów do wyboru byłby najlepszym pomysłem

**Comment by D34D-514R** [comment]
Yay! Accent colors are here!
