### ISSUE TITLE
On servers the water and lava are bugged

### ISSUE THREAD

**Issue by SRZU3IR4** [skmedix/SKlauncher#74]
**Describe the bug**
On some servers like Skycraft, the water has a bug in which we can not swim, and in the lava it has water texture.

**To Reproduce**
1. Go to 'mc.skycraft.com.br'
2. Click on any minegame
3. Swim in the water
5. Use a lava bucket
6. See error

**Expected behavior**
I hoped that I could swim in the water, and also that the lava had its normal texture.

**Screenshots**
No screenshots
**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Gbr22** [comment]
I am pretty sure that this isn't launcher related

**Comment by SRZU3IR4** [comment]
In Sklauncher 2.8 this does not happen

**Comment by skmedix** [comment]
Not really launcher related
