### ISSUE TITLE
Open any site you want on SKLauncher 3

### ISSUE THREAD

**Issue by CodeIndexer** [skmedix/SKlauncher#87]
**Description of the bug**
A bug that makes possible to open Google in SKLauncher 3

**To Reproduce**
Steps to reproduce the behavior (your default browser may open every time you click a link close or minimalize it):
1. 
![zrzut ekranu 2018-11-1 o 20 43 15](https://user-images.githubusercontent.com/39349444/47875962-3dab0680-de18-11e8-894e-4c642a00551e.png)
2. 
![zrzut ekranu 2018-11-1 o 20 44 54](https://user-images.githubusercontent.com/39349444/47875983-4bf92280-de18-11e8-8f8e-5496cebb57c8.png)

3.
![zrzut ekranu 2018-11-1 o 20 46 29](https://user-images.githubusercontent.com/39349444/47875993-55828a80-de18-11e8-9649-f26940a61a7c.png)

4.
![zrzut ekranu 2018-11-1 o 20 47 05](https://user-images.githubusercontent.com/39349444/47876011-6206e300-de18-11e8-931e-c41fa6cbacf3.png)

**Expected behavior**
Site should open only in browser, not in launcher and browser

**Bug is launcher related:**
**Environment:**
 - OS: MacOS 10.14 Mojave (This bug works on Windows and probably on Linux too!)
 - Java Version: 8u191 build 12
 - Launcher Version: 3.0.0-e8c5668

**Comment by skmedix** [comment]
Fixed!
