### ISSUE TITLE
Consider adding Brazilian Portuguese website translation by FriskNightGuard

### ISSUE THREAD

**Issue by Greg-21** [skmedix/SKlauncher#89]
In commit dd942f8227a94533740dacf07a9ba7644fe01490, in the comments section a new user, FriskNightGuard, left us a file with website translation into Brazilian Portuguese language. Unfortunately the text was translated only partially and, because I don't know Brazilian Portuguese language, I can't determine, in what percentage that translation is accurate (@TheusKhan, could you help?). Perhaps we should take a look at it.

**Comment by Greg-21** [comment]
@skmedix Could you add "Website" label? It would be great to mark with that label issues like this one.

**Comment by TheusKhan** [comment]
> In commit [dd942f8](https://github.com/skmedix/SKlauncher/commit/dd942f8227a94533740dacf07a9ba7644fe01490), in the comments section a new user, FriskNightGuard, left us a file with website translation into Brazilian Portuguese language. Unfortunately the text was translated only partially and, because I don't know Brazilian Portuguese language, I can't determine, in what percentage that translation is accurate (@TheusKhan, could you help?). Perhaps we should take a look at it.

I'll take a look.
