### ISSUE TITLE
Add Hungarian language to the site

### ISSUE THREAD

**Issue by Gbr22** [skmedix/SKlauncher#90]
I translated it a while ago and it is still not on the site. The only string that isn't translated in it is _**modern_subtext_req**_ becouse it is made so the java version is after it and that wouldn't work out in my language, (no translation is better than a bad translation). Please add it, it is 99% translated.

**Comment by skmedix** [comment]
I'll start adding languages after releasing a new version of the website. The current lang system is too buggy to roll it out for a wider audience.

**Comment by skmedix** [comment]
Added; Release in 2 days
