### ISSUE TITLE
Website translation problem

### ISSUE THREAD

**Issue by NightFurySL2001** [skmedix/SKlauncher#99]
Hello, I'm new to this SKLauncher to help out as a Chinese (Simplified) translator. Please kindly point out any problems/suggestions for me. Thanks in advance.
Problems on website translation: about half of the strings are not translated.
The webmessage_[lang].properties is a good way to start translating the website, but most of the string didn't actually show up in the website despite translated. This is amplified when there is a full sting of Latin text shows up in non-Latin text. 
Example: "I don't remember..." string in migrate account page. The corresponding translation in file, 'modal_title = "我忘了..."' is present.
![image](https://user-images.githubusercontent.com/33471049/49448186-517cca80-f813-11e8-8743-31d71e80ad06.png)
(Frankly, the "modal_title" in webmessages_en.properties is "I forgot..." which don't match the text in website)
Also, the "Modpacks" page are entirely not translated: "Modpacks are planned for next big update" and "Go back to homepage".
Corresponding string, "notready" and "button_back" are present and translated, but did not show up too.
[image](https://user-images.githubusercontent.com/33471049/49448695-660d9280-f814-11e8-975f-686cddf9fbe2.png)

Next, a few of the strings could not be translated. Most text in main page is not translatable.
(Refer to #97 )
Thank you.

**Comment by skmedix** [comment]
i18n on the website is gonna be improved asap

**Comment by NightFurySL2001** [comment]
Thanks, this problem is fixed. Also the merge for new updated words haven't show up in the website yet.

**Comment by skmedix** [comment]
Updated

**Comment by skmedix** [comment]
Follow #97 and #101
